### ISSUE TITLE
MailerLite nodes return wrong subscriber ID

### ISSUE THREAD

**Issue by raulengel** [n8n-io/n8n#10020]
### Bug Description

Whenever I use MailerLite nodes to create or get subscribers, the subscriber ID in the response is wrong.

Already tested with two different n8n instances, in different machines.

**Example subscriber IDs**
**Correct:** 113280109331350776
**Wrong:** 113280109331350780

It also returns the wrong group ID when searching a subscriber by email. If I want to know to which group ID the subscriber belongs to, I won't be able to because of the wrong ID.

**Example group IDs**
**Correct:** 113276040087864466
**Wrong:** 113276040087864460

I can confirm this issue by making a custom HTTP request, which returns correct ID values.

## Outputs
![image](https://github.com/user-attachments/assets/5b928f74-d726-4ee6-bf9c-b26f4943c8a7)
![image](https://github.com/user-attachments/assets/cbac2a34-600c-40dc-8c21-c7feab51ef3b)

### To Reproduce

Make a request using the MailerLite node to create or get subscribers.

### Expected behavior

Give me the correct subscriber ID.

### Operating System

Ubuntu 22.04

### n8n Version

1.49.0

### Node.js Version

default

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @raulengel 

Thanks for the report, the issue here is down to a change with the Mailerlite api.

We currently use the old api which  returns the id as a number but the new api which you are using in the http request node returns it as a string.

We have a dev ticket open internally already to update the api version that the node is using. I will add this issue to that ticket.
