### ISSUE TITLE
Migration need permission on pg_database which seems excessive.

### ISSUE THREAD

**Issue by SoulKyu** [n8n-io/n8n#10061]
### Bug Description

If the permissions on pg_catalog is revoked, we are unable to perform an upgrade of n8n : 
**User settings loaded from: /home/node/.n8n/config
Last session crashed
Initializing n8n process
n8n ready on 0.0.0.0, port 8000
Migrations in progress, please do NOT stop the process.
Starting migration AddConstraintToExecutionMetadata1720101653148
Migration "AddConstraintToExecutionMetadata1720101653148" failed, error: permission denied for table pg_database
Error: There was an error running database migrations
QueryFailedError: permission denied for table pg_database
**

### To Reproduce

1. Revoke access on pg_catalog
2. Try to upgrade n8n

### Expected behavior

pg_database permission seems excessive as it allow the  users to get the list of all the database present on the postgres instance

### Operating System

docker

### n8n Version

1.50.0

### Node.js Version

any

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by netroy** [comment]
This is a valid concern, but fixing this would require fixing the DB abstraction library (typeorm) that we use, which (unfortunately) is largely unmaintained.
That's why this is unfortunately currently not on our roadmap because of a huge list of tasks with much higher priority. 

As a potential workaround we recommend running a dedicated postgres server for n8n, to ensure complete isolation of n8n from any other databases.
