### ISSUE TITLE
Splunk node can't create search jobs where the start and/or end times are relative specifiers (e.g. `-1d@d`)

### ISSUE THREAD

**Issue by jreyesr** [n8n-io/n8n#10447]
### Bug Description

The **Create Search Job** action on the Splunk node doesn't accept Splunk's relative time specifiers on the appropriate time fields, namely Earliest Index, Earliest Time, Latest Index and Latest Time. Splunk's API supports providing not only exact timestamps, but also strings that represent times relative to the current time, such as "a day ago" or "an hour ago, rounded to the start of the hour". See [the docs](https://docs.splunk.com/Documentation/SCS/current/Search/Specifyrelativetime). However,, the N8N node only supports either fixed timestamps, selected via the datetime picker, or expressions that resolve to an ISO8601 time, but not relative specifiers like `-1d@d` that can be passed directly to Splunk.

### To Reproduce

1. Add a Splunk node with the "Create a Search Job" action
2. Set the "Earliest Time" or "Latest Time" fields to an Expression containing a value in [Splunk's relative time format](https://docs.splunk.com/Documentation/SCS/current/Search/Specifyrelativetime) (for example, `-1d@d` means "1 day before now, rounded to the start of the day", AKA yesterday; or `now` which is commonly used as a latest time). Setting an Expression is necessary because Fixed force the selection of an actual datetime using the datetime picker
3. Fill any other necessary fields, namely the Query
4. Run the note
5. If using a real Splunk instance, the search will run with no time limits. By intercepting the request or sending it to a fake server, it's possible to see that the parameter that contained a relative time has been passed as `NaN`

See below: I started a netcat listener on port 8089, configured a Splunk credential that pointed to that listener as the "base URL", and then ran the request:

![image](https://github.com/user-attachments/assets/638fc971-b0a2-4e08-be19-4c5372eb79dd)

Note how the Latest Time is set to `now`. The request that would have been sent to the Splunk server is as follows:

![image](https://github.com/user-attachments/assets/38aaf44e-5f11-45c9-ac72-9356f4fb3cbb)

```
POST /services/search/jobs HTTP/1.1
Accept: application/json
Content-Type: application/x-www-form-urlencoded
...

search=myquery&earliest_time=1723757641&latest_time=NaN


### Expected behavior

The Create Search Job action in the Splunk node should support relative times on the timestamp fields, since those are used  elsewhere (e.g. in Splunk's web UI). When a relative time specifier is provided, it should be passed directly for Splunk to interpret.

### Operating System

Docker

### n8n Version

1.54.4

### Node.js Version

20.15.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @jreyesr,

We have created an internal ticket to look into this which we will be tracking as "GHC-167"

**Comment by jreyesr** [comment]
Thanks! Please let me know if you'd like any more information

**Comment by Joffcom** [comment]
Hey @jreyesr 

It looks like the node is working as expected as we are after a date  and we don't currently support the relative time options.

As this is currently expected behaviour there isn't really anything to "fix" here, I will get a feature request created on our [support forum](https://community.n8n.io) for this shortly and we can look at adding this next time we make any changes to the node or between tasks as it sounds like we would just need to add a new text field for the option or a bool to toggle between date input or relative input.

For now I am going this issue let me know if you have any questions on this.

**Comment by kundeng** [comment]
Are you serious?  This splunk node doesn't work at all.  As a splunk SME, I was excited then extremely disappointed.  Everything about this node is wrong: it hang, it doesn't parse time correctly.

**Comment by kundeng** [comment]
Still present in n8n 2.38.7 (current release). Revisiting this with source references and measurements, because I think the "working as expected" reading understates the outcome.

`toUnixEpoch` is `Date.parse(timestamp) / 1000` (`v2/helpers/utils.js`). `Date.parse` returns `NaN` for every Splunk relative specifier, and the literal string `NaN` is then sent as `earliest_time`. Splunk accepts it with **HTTP 201 and silently ignores the bound** — so the search does not fail, it runs over a wider range than requested.

Measured against Splunk 10.2.1, `search index=_internal | stats count`:

| `earliest_time` sent | events returned |
|---|---|
| `-5m` (what the user typed) | 1,462 |
| `NaN` (what the node sends) | 12,027 |
| omitted (all time) | 12,029 |

So the node returns ~8x the requested data and reports success. An unsupported input that errors is "not supported"; an unsupported input that silently widens the search is a correctness bug — for alerting or any rate-based logic it produces wrong numbers that look right.

Splunk's API accepts `-1d@d`, `-15m` and `-24h` directly (201 each), so no conversion is needed for relative values.

Filed with full details and reproduction as #38530. Three other defects in the same node found alongside it: #38527 (`exec_mode=oneshot` always throws on an unconditional `response.sid` deref), #38528 (`setReturnAllOrLimit` reads parameters from item index 0, so `getResult` returns empty for every item after the first), #38529 (`json: true` + `parseXml()` are mutually exclusive; the parse failure retries the POST, dispatching 6 Splunk jobs per execution and still reporting success).

For anyone hitting this meanwhile: a working flow is builtin `search:create` (leave `exec_mode` at default) -> Wait -> builtin `search:get` -> If on `isDone` (false branch loops back to Wait) -> an HTTP Request node for `/services/search/jobs/{sid}/results`. That avoids `getResult` and `oneshot` entirely, and passes relative times on the HTTP node where they are not mangled.
