### ISSUE TITLE
Need OAuth2 API for TikTok conection

### ISSUE THREAD

**Issue by slv1221** [n8n-io/n8n#11119]
### Bug Description

It is necessary to change the name of the parameter client_id to client_key

https://www.tiktok.com/v2/auth/authorize/?client_key=<client_key>&response_type=code&scope=<scope>&redirect_uri=<redirect_uri>&state=<state>

### To Reproduce

go to credentials
add new credentials for OAuth2 API 

### Expected behavior

incorrect link structure

### Operating System

Ubuntu 22

### n8n Version

1.61.0

### Node.js Version

12.22.8

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @slv1221,

We have created an internal ticket to look into this which we will be tracking as "GHC-288"

**Comment by Joffcom** [comment]
Hey @slv1221 

This looks like a feature request rather than a bug, our OAuth2 implementation currently tries to stick to the standard which uses `client_id`.

Would you be able to open a feature request on our [support forum](https://community.n8n.io) for custom oauth2 fields and we can see if it is something the community would be after.
