### ISSUE TITLE
Webhook node options ignore bots bug

### ISSUE THREAD

**Issue by lucalamo** [n8n-io/n8n#11176]
### Bug Description

When ignore bots flag is setted, postman requests are rejected.
Is this options working? Could you please add postman user agent to allow postam requests?

### To Reproduce

create a webhook node
set ignore bots options to true

### Expected behavior

ignore bots allow postman requests

### Operating System

ubuntu 22.04

### n8n Version

1.60.1

### Node.js Version

18.17.1

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @lucalamo,

We have created an internal ticket to look into this which we will be tracking as "GHC-299"

**Comment by Joffcom** [comment]
Hey @lucalamo,

This does not look like a bug to me, Postman is classified as a bot in the package we use and is listed here: https://user-agents.net/bots/postman-runtime

If you want to use Postman for testing the quickest option would be to add a `User-Agent` header to your request to override the default, you can set it to a value like `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36` and it will do the job.

As this is not a bug and is intentional I am going to mark this as closed, Let me know if you have any questions on this.
