### ISSUE TITLE
Webhooks return 404 after restarting n8n

### ISSUE THREAD

**Issue by syphernl** [n8n-io/n8n#1122]
**Describe the bug**
We run our n8n on AWS Fargate. 
If we deploy a new update (e.g. from 0.89.2 to 0.90.0, 0.90.0 to 0.91.0) and the container restarts the webhooks are not longer working and requires the workflow to be saved again in the frontend for them to become active.

Test workflow:
![image](https://user-images.githubusercontent.com/639906/97968177-92ded180-1dbe-11eb-9daf-fd4acee7498a.png)

During the container start it reports that the workflows are started:
```txt
2020-10-27 07:36:28 => Started
2020-10-27 07:36:28 Editor is now accessible via:
2020-10-27 07:36:28 https://localhost:5678/
2020-10-27 07:36:27 => Started
2020-10-27 07:36:27 - Service Desk Customer JIRA - list Customer Done tickets that are linked to SD tickets
2020-10-27 07:36:27 => Started
2020-10-27 07:36:27 - GitLab webhook - Customer Community db
2020-10-27 07:36:27 => Started
2020-10-27 07:36:27 - GitLab webhook - Customer Community api
2020-10-27 07:36:27 => Started
2020-10-27 07:36:27 - Customer - Auto remove containers [CRON]
2020-10-27 07:36:27 => Started
2020-10-27 07:36:27 - Receive YouTube still
2020-10-27 07:36:27 => Started
2020-10-27 07:36:27 - Slack slash command - Stencil Launcher
2020-10-27 07:36:27 => Started
2020-10-27 07:36:27 - Customer - JIRA In Test and Review & GitLab MR's daily overview to Slack
2020-10-27 07:36:27 ================================
2020-10-27 07:36:27 Start Active Workflows:
2020-10-27 07:36:27 ================================
2020-10-27 07:36:27 - URL to Slack
2020-10-27 07:36:27 n8n ready on 0.0.0.0, port 5678
2020-10-27 07:36:27 Version: 0.90.0
2020-10-27 07:36:24 UserSettings got generated and saved to: /home/node/.n8n/config
```
However, the webhooks of those workflows do not work.

**To Reproduce**
1. Create a Workflow with a webhook (simple GET will suffice). Set it to active and save it.
2. Test the webhook (`curl -x GET https://example.com/webhook/0ff123c4-11a3-4d45-8db4-e5b218b4ff06`), it works: 
   ```yaml
   {
      "message": "Workflow got started."
   }
   ```
3. Restart the n8n container
4. Execute the webhook again (`curl -x GET https://example.com/webhook/0ff123c4-11a3-4d45-8db4-e5b218b4ff06`). It will now return:
   ```yaml
   {
      "code": 404,
      "message": "The requested webhook \"GET 0ff123c4-11a3-4d45-8db4-e5b218b4ff06\" is not registered."
   }
   ```
5. Save the workflow in the frontend
6. Execute the webhook again (`curl -x GET https://example.com/webhook/0ff123c4-11a3-4d45-8db4-e5b218b4ff06`). It will now return:
   ```yaml
   {
     "message": "Workflow got started."
   }
   ```

**Expected behavior**
I expect the webhooks to be functional when n8n restarts.

**Environment (please complete the following information):**
We are using the pre-built Docker container `n8nio/n8n:0.91.0`

**Additional context**
We do not have/use persistent storage and provide all required configuration via environment variables (e.g. `N8N_ENCRYPTION_KEY`).

**Comment by janober** [comment]
I just tested but I am sadly not able to reproduce this. I used the following docker command:
```bash
docker run -it --rm \
	--name n8n \
	-p 5678:5678 \
	-v ~/.n8n:/root/.n8n \
	n8nio/n8n:0.91.0
```

And for me, the workflow can be started via webhook fine after I stopped and restarted the container.

What kind of database are you using?

**Comment by syphernl** [comment]
We are using PostgreSQL 12.3 on RDS. 

Could it be that anything regarding the webhooks is being stored in `/root/.n8n`? 
Because with each reboot this essentially gets cleared out since we do not use a volume and provide all data directly using env vars.

**Comment by janober** [comment]
No that should not be a problem.

I did just run a second test with a locally running Postgres database with this command (so also no persistent volume and with Postgres):
```
docker run -it --rm \
  --name n8n \
  --network=host \
  -e N8N_ENCRYPTION_KEY=XXXX \
  -e DB_TYPE=postgresdb \
  -e DB_POSTGRESDB_USER=XXXX \
  -e DB_POSTGRESDB_PASSWORD=XXXX \
  n8nio/n8n:0.91.0
```
Also this worked fine for me.

So sorry, sadly do not see a way how I can reproduce and so fix the issue you are facing.
Can you please try to reproduce it locally and then send me docker-commands for it. Thanks!

**Comment by syphernl** [comment]
Fargate 1.4.0 uses Containerd instead of the Docker Engine (which uses Containerd itself but adds some additional things). 
But the Docker equivalent of running it probably be something like this:
```
docker run -it --rm \
  --name n8n \
  -p 5678:5678 \
  -e DB_POSTGRESDB_SCHEMA=public \
  -e DB_TYPE=postgresdb \
  -e GENERIC_TIMEZONE='Europe/Amsterdam' \
  -e N8N_BASIC_AUTH_ACTIVE=true \
  -e N8N_PROTOCOL=https \
  -e NODE_ENV=production \
  -e NODES_EXCLUDE='["n8n-nodes-base.executeCommand","n8n-nodes-base.writeBinaryFile","n8n-nodes-base.readBinaryFile","n8n-nodes-base.writeBinaryFiles"]' \
  -e VUE_APP_URL_BASE_API='https://app.example.com' \
  -e WEBHOOK_TUNNEL_URL='https://app.example.com' \
  -e N8N_BASIC_AUTH_USER=XXXX \
  -e N8N_BASIC_AUTH_PASSWORD=XXXX \   
  -e N8N_ENCRYPTION_KEY=XXXX \
  -e DB_POSTGRESDB_HOST=XXXX \
  -e DB_POSTGRESDB_PORT=XXXX \
  -e DB_POSTGRESDB_USER=XXXX \
  -e DB_POSTGRESDB_PASSWORD=XXXX \
  -e DB_POSTGRESDB_DATABASE=XXXX \
  n8nio/n8n:0.91.0
```

**Comment by janober** [comment]
If you say "probably something like that" sounds like you did not actually test if you can reproduce the problem like that.

**Comment by syphernl** [comment]
I have tested it with a simplified example:

```
docker run -it --rm \
  --name n8n \
  -p 5678:5678 \
  -e GENERIC_TIMEZONE='Europe/Amsterdam' \
  -e N8N_PROTOCOL=http \
  -e NODE_ENV=production \
  -e NODES_EXCLUDE='["n8n-nodes-base.executeCommand","n8n-nodes-base.writeBinaryFile","n8n-nodes-base.readBinaryFile","n8n-nodes-base.writeBinaryFiles"]' \
  -e N8N_ENCRYPTION_KEY=abcdef \
  -v ~/.n8n:/root/.n8n \
  n8nio/n8n:0.91.0
```

In this case the webhooks just work fine after a restart of the container. I have to do some more extensive checks with Postgresql attached to it.

**Comment by janober** [comment]
Yes, that would be great. Because unless you are able to reproduce it, it will be impossible for me too.

**Comment by syphernl** [comment]
I am unable to reproduce it with this Docker setup:
```
docker run -d \
    --name test-postgres \
    -e POSTGRES_PASSWORD=testtest \
    postgres                      

docker run -it --rm \
  --name n8n \
  -p 5678:5678 \
  -e DB_POSTGRESDB_SCHEMA=public \
  -e DB_TYPE=postgresdb \
  -e GENERIC_TIMEZONE='Europe/Amsterdam' \
  -e N8N_BASIC_AUTH_ACTIVE=true \
  -e N8N_PROTOCOL=https \
  -e NODE_ENV=production \
  -e NODES_EXCLUDE='["n8n-nodes-base.executeCommand","n8n-nodes-base.writeBinaryFile","n8n-nodes-base.readBinaryFile","n8n-nodes-base.writeBinaryFiles"]' \
  -e VUE_APP_URL_BASE_API='http://localhost:5678/' \
  -e WEBHOOK_TUNNEL_URL='http://localhost:5678/' \
  -e N8N_BASIC_AUTH_USER=test \
  -e N8N_BASIC_AUTH_PASSWORD=test \
  -e N8N_ENCRYPTION_KEY=abcdef \
  -e DB_POSTGRESDB_HOST=172.17.0.2 \
  -e DB_POSTGRESDB_PORT=5432 \
  -e DB_POSTGRESDB_USER=postgres \
  -e DB_POSTGRESDB_PASSWORD=testtest \
  -e DB_POSTGRESDB_DATABASE=postgres \
  n8nio/n8n:0.91.0
```

Also tried a migration path (`0.90.0` > `0.91.0`) to see if this makes any difference but the webhooks keep on working.

I even tried running n8n straight on containerd:

```
sudo ctr image pull docker.io/n8nio/n8n:0.91.0

sudo ctr run -t -rm --net-host \
  -env DB_POSTGRESDB_SCHEMA=public \
  -env DB_TYPE=postgresdb \
  -env GENERIC_TIMEZONE='Europe/Amsterdam' \
  -env N8N_BASIC_AUTH_ACTIVE=true \
  -env N8N_PROTOCOL=https \
  -env NODE_ENV=production \
  -env NODES_EXCLUDE='["n8n-nodes-base.executeCommand","n8n-nodes-base.writeBinaryFile","n8n-nodes-base.readBinaryFile","n8n-nodes-base.writeBinaryFiles"]' \
  -env VUE_APP_URL_BASE_API='http://localhost:5678/' \
  -env WEBHOOK_TUNNEL_URL='http://localhost:5678/' \
  -env N8N_BASIC_AUTH_USER=test \
  -env N8N_BASIC_AUTH_PASSWORD=test \
  -env N8N_ENCRYPTION_KEY=abcdef \
  -env DB_POSTGRESDB_HOST=172.17.0.2 \
  -env DB_POSTGRESDB_PORT=5432 \
  -env DB_POSTGRESDB_USER=postgres \
  -env DB_POSTGRESDB_PASSWORD=testtest \
  -env DB_POSTGRESDB_DATABASE=postgres \
  docker.io/n8nio/n8n:0.91.0 n8n
```

Even after restarting and recreating this container the webhook works. 
Is there any way of increasing log verbosity to see what is going on? I couldn't find this in the docs.

**Comment by janober** [comment]
Sorry totally missed your question.

No, sadly not. Logging is one of the things that is currently still very bad in n8n.

**Comment by dsferruzza** [comment]
Hi!

I believe I have a similar issue.

## Context

I'm using n8n `0.104.2` deployed on [Clever Cloud](https://www.clever-cloud.com/en/).
It is connected to a managed PG 11 instance, and a n8n encryption key is setup.
I have a test workflow that is active and only contains a webhook trigger; when I run `curl https://myinstance/webhook/uuid` I get HTTP 200 `OK`.

When I restart my app, Clever Cloud actually boots a new VM that runs the new app, waits until the app listens on a given port, redirects traffic from their reverse proxy to the new VM/app, and then a bit later kills the old VM. Classic blue-green deployment.

## Issue

What happens here is that my test workflow's webhook work just fine during deployment (old VM) and after deployment ended (new VM). But after a short time (which I believe is when the old VM is killed), I get a 404 error.

I checked the DB and I noticed a few things:
1. In the `workflow_entity` table, my test workflow is always marked as active (which is normal)
2. In the `webhook_entity` table, the line corresponding to my test workflow disappears a short time after deployment succeeded (which I guess is why I get a 404 error)
3. The line reappears when I save my test workflow from the UI, and this fixes the issue until next deployment

## Intuition

I was not able to verify this but this make me think that there may be some kind of mechanism that unregisters webhooks when n8n server is killed (like a reaction to SIGTERM). Would this make sense?

---

Any idea of what is going on?
It seems that I can easily reproduce the issue on my instance, so let me know if I can do something to investigate further!

**Comment by janober** [comment]
Ah yes that makes sense then. You currently have to make sure that the old process gets stopped before you start the new one.

**Comment by dsferruzza** [comment]
Oh. I believe this happens here, right? https://github.com/n8n-io/n8n/blob/master/packages/cli/commands/start.ts#L65-L114

If my guess is correct, current implementation ensures no more workflows can be triggered after SIGTERM was received, so that n8n can finish current workflow executions and then die, right?

In a single node _without_ blue-green deployment this prevents n8n to keep accepting webhook requests (thus starting new executions) so that it would stop at some point soon, at the cost of any webhook calls during the shutdown being simply refused/lost. This might make sense in some contexts, like when the n8n instance is non critical.

But when deploying using blue-green deployment, the point is usually to avoid losing any request at all. We have to trust the reverse proxy to not forward new requests to the old app's instance so that it could die gently.
Also, blue-green deployment is a prerequisite for automatic up/down-scaling (both horizontal and vertical) which is not necessary in my actual context but might be needed by users that have a high load n8n instance.

I don't know n8n very well yet, but it seems to be a wonderful tool and I plan on using it more in the future.
In my perspective, if I want to use it on tasks that requires reliability, it has to play well with blue-green deployment so that it would stay available during deployments.
One of the reasons why I use Clever Cloud is because my deployment is fully automated and their team can (and regularly does) trigger re-deployments of my apps for maintenance purposes (security fixes, up/down-scaling, ...) without me worrying about anything.

Maybe the simplest way to make it work in both contexts would be to add an new boolean configuration value, like `N8N_DROP_INCOMING_WEBHOOK_REQUESTS_WHEN_SHUTTING_DOWN` that would be `true` by default (= current behavior). If this variable is set to `false`, shutdown procedure would be the same except webhooks (and maybe test webhooks?) would stay active; in practice the reverse proxy would have stopped to forward new requests anyway (but the new instance would receive them and the _service_ would stay available!).

What is your point of view on this subject?

**Comment by janober** [comment]
Ah yes totally agree with you and I am aware that the current behavior is not great. But having said that I do not want to make any changes here for now. The reason is that we are currently working on something related which is making n8n scale better. You can find the PR here:
https://github.com/n8n-io/n8n/pull/1340

On base of that, are we also working on modularizing the incoming webhook part. Meaning you can in the future simply start as many workers and webhook-services as you want. You can then also stop, start and update them anytime. So that will then also solve your problem.

Hope that makes sense.

**Comment by dsferruzza** [comment]
It is hard to understand the PR's code without having seen any design intention, but the way you tell it seems cool! Can't wait to see that!

---

> I do not want to make any changes here for now

If by that you mean:

1. this part should not be changed now because it will be decommissioned/refactored soon → neat!
2. **you** do not want to touch this right now and the improvements are not to be expected soon → let me know; I might try to land a PR

---

> Meaning you can in the future simply start as many workers and webhook-services as you want. You can then also stop, start and update them anytime.

You mean that it you will make it possible to have workers and webhook-services as external apps/processes that work for the main instance? Or is it an internal refactoring of how the server monolith could work/scale better? Or are we talking "fully-distributed system" (I guess not)?

**Comment by krynble** [comment]
Hello @dsferruzza 

A few updates about this discussion:

- We added a new setting to n8n (you can set it using env vars) that works best for blue/green deployments. You can see more here: https://github.com/n8n-io/n8n/blob/e53efdd337a100faad781f80868447b590d893b6/packages/cli/config/index.ts#L473

What happens under the hood, just like you mentioned, is that n8n registers and deregisters webhooks on startup / shutdown.
This flag prevents n8n from deregistering on shutdown, allowing you to better use blue/green deployments.

Please do note that n8n was not build to handle this scenario completely, so if you have triggers that are based on events other than webhooks, n8n might cause duplication of work. 

An example: let's say you have a workflow that reads data from a database every x seconds. If you have two n8n instances (blue / green) then BOTH are actually working, so this is something to watch for.

- This changes will probably be available on next n8n version. We have been working on this issue for some time and you can now scale n8n a lot more than previously. This is a work in progress and we are writing the docs for these features.

> You mean that it you will make it possible to have workers and webhook-services as external apps/processes that work for the main instance? Or is it an internal refactoring of how the server monolith could work/scale better? Or are we talking "fully-distributed system" (I guess not)?
Yes! We want to go for fully distributed system but for now we have already split n8n into 3 separate services: main process (with editor interface, internal API and job scheduling), workers (you can have as many as you want) and webhook processes (that are responsible for parsing and handling all HTTP requests, allowing you to scale these services).

I will keep this issue open but I highly encourage you to test this new setting once it is available. Should solve the issues you are now facing.

**Comment by dsferruzza** [comment]
I just tested `N8N_SKIP_WEBHOOK_DEREGISTRATION_STARTUP_SHUTDOWN=true` with n8n `0.108.0` and it seems to fix my issue! Thanks a lot!

I understand that triggers other than webhooks might be triggered more than once in parallel; this feels an acceptable counterpart in my case. This is quite common in a lot of distributed systems: "at most once delivery" and "at least once delivery" are easier to achieve compared to "exactly once delivery"...

Thanks for explaining the vision on this part for the future of n8n. I think I'll keep an eye on this! Do you intend to release this on the fly (step by step) or does this requires deep changes that will be released at once in a big major version?

_From my perspective, this issue could be closed; I'll let you do it if you feel that there is nothing more here and that @syphernl's problem is fixed too._

**Comment by DavraYoung** [comment]
If anyone experience such error:
The solution is:
Either turn of Zero Down Time
Or use N8N_SKIP_WEBHOOK_DEREGISTRATION_SHUTDOWN="true"


Reason why this happens:
N8N cleans webhook_entity table on stop and you probably use Zero Down Time.

If you restart n8n with zero down time in mind, the old n8n instance will be waiting for new one to start and gets stopped only when the newly one starts working. And because the old one cleans the webhook_entity table, the new n8n will get empty tables on start, which then leads to 404 error

**Comment by dpessoaIGC** [comment]
@DavraYoung Could you indicate or link documentation on how to turn off Zero Down Time?
