### ISSUE TITLE
Regression: Airtable Node - Search Record - FAILS when On Error "Continue (using error output)" set

### ISSUE THREAD

**Issue by dkindlund** [n8n-io/n8n#11233]
### Bug Description

Hey @Joffcom, I think this issue *might* be related to https://github.com/n8n-io/n8n/issues/11202, but I'm not 100% sure.

Essentially, if I create any Workflow using an Airtable node for Search Record and specify an On Error value of `Stop Workflow` OR `Continue`, that node works *perfectly*.  HOWEVER, if I specify an On Error value of `Continue (using error output)`, then the node SILENTLY RETURNS NOTHING ALWAYS.

This is definitely a *regression* -- this functionality used to work before v1.62.4.

### To Reproduce

1. Setup n8n v1.62.4
2. Create new Workflow
3. Add Airtable Search Record node with On Error `Stop Workflow`
4. Test the Airtable node, verify that it does return at least one record with your filter
5. Switch Airtable node to On Error `Continue (using error output)`
6. Test the Airtable node with the *same filter* and validate that NOTHING is returned.

### Expected behavior

I expect the Airtable node's On Error value of `Continue (using error output)` should work without breaking logic.

### Operating System

Google Cloud Run

### n8n Version

1.62.4

### Node.js Version

18.16.0

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @dkindlund,

We have created an internal ticket to look into this which we will be tracking as "GHC-309"

**Comment by dkindlund** [comment]
And I can't downgrade to an earlier version, because the recent DB migrations have *broken* the app with my database:
```
QueryFailedError: column User.apiKey does not exist
```

Any ETA on when this issue *might* be fixed, @Joffcom ?

**Comment by dkindlund** [comment]
It would be wonderful, if the n8n dev team could add 3 simple "unit tests":
* Airtable Search Record / On Error / Stop Workflow
* Airtable Search Record / On Error / Continue
* Airtable Search Record / On Error / Continue (using error output)

It feels like like a 2-node workflow for each of these unit tests would have easily caught this regression...

**Comment by dkindlund** [comment]
I've confirmed that this issue impacts the following Airtable operations:
```
search: record
update: record
```
... I suspect (maybe all?) other Airtable operations are also impacted.

**Comment by Joffcom** [comment]
Hey @dkindlund 

This is something we will likely look into on Monday, it also impacts the Postgres node so there is a good chance others are impacted.

I have just raised it internally to see if anyone is working today but I don't expect anyone to be around.

We will likely add a test to the core of n8n for this instead of to the node but if you wanted to create a test for the node that covers this I can review the PR and get it merged.

**Comment by Joffcom** [comment]
@pdondin We are currently working on fixing this, It turns out it is not ANY node using the error output that is impacted it is any node using the error output that is also set up to be available as an AI tool which is 22 nodes in total.

As a temporary solution not using the error output and taking the old method of continue on fail then use an if node to handle the errors will still work or there is a command that be used to rollback the db migration by stopping n8n and running `n8n db:revert` then going back to a previous version.

**Comment by pdondin** [comment]
Thanks for your answer @Joffcom 
It makes actually sense now, I said "ANY" after checking on a slack node, but it is also in the AI Tools 😅

About the db:revert ; should I mention any version ID or will it work directly ? 
_(bc I have to many node working on the error output ; bulk updating nodes is such a pain)_

**Comment by janober** [comment]
Fix got released with [`n8n@1.62.6`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.62.6)

**Comment by dkindlund** [comment]
@Joffcom and @janober -- wonderful!  Thanks for your help -- we'll try this new version out as soon as the docker images are available on ghcr.

**Comment by netroy** [comment]
The docker images should be on GCHR already. we now create releases only after the version is available on NPM, DockerHub, and GHCR.
