### ISSUE TITLE
Http Request: Batching partly pretends batching

### ISSUE THREAD

**Issue by wodor** [n8n-io/n8n#11516]
### Bug Description

Batching is an incredibly helpful feature, but it only partly works. 
currently it looks like that node is waiting, without making any request, for a time that is [interval] x [number of items] and then does the requests for all items at once (or consecutively, but without any waits for sure).

It would be perfect if one request is made, then one interval of wait is made, then next request ...   

### To Reproduce

create a http request node 
generate 10 items 
configure node to use batching, size of 1, 500ms interval
open the debug console 
see that all requests are made after 5 seconds, all at once  
 

### Expected behavior

in this situation we should see first request made after only  500ms, then next requests are made every 500ms.

Only this way of working really helps to deal with APIs with aggressive throttling policies. 

### Operating System

mac os docker 

### n8n Version

1.64.3

### Node.js Version

v20.18.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @wodor,

We have created an internal ticket to look into this which we will be tracking as "GHC-380"

**Comment by Joffcom** [comment]
@wodor,

I have just taken a look at this using webhook.site, If I generate 4 items and use a batch of 2 and a wait of 5000 it is making 2 http requests then waiting 5 seconds before making the next 2.

![image](https://github.com/user-attachments/assets/ee172b41-99b1-4372-9511-6fe1a2f27da8)

If I do the same 4 items with batch size of 1 and a 500ms wait I get 1 sent every half a second which seems right to me.

![image](https://github.com/user-attachments/assets/98116f08-16ce-47d2-9640-f4ceb4cd1648)

Rather than checking the debug console what happens if you check the actual destination you are sending to? The debug console might be a bit out as it has to wait for the server to send messages back with the data, As a quick test I added a post body of `time` to my request and used `{{ $now.format('mm:ss:SSS') }}` as the value by doing this I found that the first 2 requests are actually sent almost at once then it waits to send the next ones but in the console log you see them returned at the same time.

Apart from the first and second item actually being sent almost at once I am not sure there is a bug here and I think what you are after is a more realtime debug option so it updates after each item has sent rather than when the node finishes.

**Comment by wodor** [comment]
ok,  maybe I was misled...  Give me a day. I'll test on with a server  where I can log requests.

**Comment by Dejo-commerce** [comment]
I wonder if the batching parameter also applies for the pagination or if all pages are requested immediately.

**Comment by Joffcom** [comment]
Moving to closed for now as we don't believe there is a bug to be fixed. If we can get a way to reproduce a bug here we can open this again.
