### ISSUE TITLE
Form ending responds with an error when adding expressions in Completion Title or Completion Message inputs

### ISSUE THREAD

**Issue by nikoada** [n8n-io/n8n#11749]
### Bug Description

In Form Ending node there is an error
Form ending responding with an error
"Problem submitting response
Please try again or contact support if the problem persists"
when expression is used in Completion Title or Completion Message inputs
<img width="435" alt="Screenshot 2024-11-14 at 23 48 05" src="https://github.com/user-attachments/assets/0c88daff-e039-4a20-b44c-5daf7cd9baab">
<img width="905" alt="Screenshot 2024-11-14 at 23 52 55" src="https://github.com/user-attachments/assets/e2ca8a44-3f41-4c4c-bc67-fd478ab50af1">

### To Reproduce

1. Add On Form Submission trigger
2. Add Field to Form trigger
3. Connect with Form Ending
4. Add an expression, anything from a previous schema to the Completion Title or Completion Message

### Expected behavior

In form ending node, successfully adding expressions in inputs is expected.

### Operating System

CentOS 8-based virtual private server (VPS)

### n8n Version

1.66.0

### Node.js Version

not Sure (Reilway)

### Database

PostgreSQL

### Execution mode

queue

**Comment by Joffcom** [comment]
Hey @nikoada,

We have created an internal ticket to look into this which we will be tracking as "GHC-446"

**Comment by dongphuchaitrieu** [comment]
I want to create a form and redirect to a URL in Form Ending, but I always encounter an error.
"Problem submitting response
Please try again or contact support if the problem persists"

**Comment by fkrauthan** [comment]
I don't think that issue is fixed. I am running n8n version `1.69.2` (using docker). And when submitting a form that has a end form with placeholders the `POST` and `GET` call to n8n from the prod form seem to be never succeeding (the progress indicator on the submit button is active). While in the backend Executions list I can see that the workflow has finished (and has triggered the expected end form node).
