### ISSUE TITLE
Slack Node create empty channel without users

### ISSUE THREAD

**Issue by arkhelieldan** [n8n-io/n8n#1175]
**Describe the bug**
Hello everyone.
I`m using Slack node to create the Channel with invited users.
But when i run the node, the Channel is created but without users.

**To Reproduce**
1. Add slack node
2. Setup the Auth for Slack bot.
3. Set Resource: Channel
4. Set Operation: Create
5. Set Channel: namechannel
6. Set Fields Users, and add the contacts in the box.

**Expected behavior**
Creation of Channel with the users configured in node
**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu Linux 18.04]
 - n8n Version [e.g. 0.93.0]
 - Docker compose

**Comment by RicardoE105** [comment]
@arkhelieldan Found the issue. The `user ids` field it's not supposed to be shown when creating a channel. In order to invite users to a channel `channel:invite` has to be used. Sadly found a bug there as well. Either way, both got fixed and in next release, you should be able to invite users to a channel. 

Thanks very much for putting that together.

**Comment by arkhelieldan** [comment]
Great @RicardoE105!
thanks for your help.

**Comment by janober** [comment]
Got released with n8n@0.95.0
