### ISSUE TITLE
ACID Google Sheets

### ISSUE THREAD

**Issue by carlosbaraza** [n8n-io/n8n#1208]
**Describe the bug**
If a workflow executes multiple times and each execution appends to a Google Sheet, the data will be inconsistent if it is appended too often.

**To Reproduce**
1. Create a workflow that adds appends to a google sheet.
2. Execute the workflow many times through a webhook (for example)

**Expected behavior**
A lock to happen across different workflow executions to prevent having inconsistent data in Google Sheets.

**Comment by janober** [comment]
Sorry, do not understand.
What you describe sounds to me exactly what I want to happen in such a case. Can you please elaborate a little bit. Thanks!

**Comment by carlosbaraza** [comment]
# Testing context

Workflow: Get data from webhook, modify a bit, and append to Google Sheets.
![Screenshot 2020-11-26 at 09 27 58](https://user-images.githubusercontent.com/1270425/100332767-b108ad80-2fc9-11eb-95c3-5bff0019a3d8.png)

Webhook call:
```
async function main(number) {
  try {
    const response = await fetch(url, {
      method: "POST",
      body: JSON.stringify({
        number,
      }),
      headers: { "Content-Type": "application/json" },
    });

    console.log("Response status", response.status);
  } catch (error) {
    console.log(error);
  }
}

for (let index = 0; index < 20; index++) {
  setTimeout(
    () => main(index),
    index * 500
  );
}
```

# Observations
If the interval time is reduced to about 500ms, mocking a peak of traffic:
* The web server (4GB RAM, 2 vCPU, DigitalOcean) stops responding (DoS) above 30 concurrent requests. If we wanted this to be robust and reliable, the server should pick the data up and add it to the queue to be processed later. However, it hangs completely, probably because the JS event loop is busy with other tasks. This might be an issue itself.
* If two different executions of the same workflow are happening in parallel, there is a race condition, and the result would be some data being dropped (check the following spreadsheet screenshot).
![Screenshot 2020-11-26 at 09 26 14](https://user-images.githubusercontent.com/1270425/100333989-1d37e100-2fcb-11eb-8cda-b32de7f6dfc5.png)

# Expected behavior
No matter how many requests I'm sending in parallel (to a certain degree), the data at the end should be consistent. For example, if I send 100 concurrent requests following the example above with 0 interval time, I should get 100x 200 status codes, and after a while, when all the workflow queue is completed, I should have a table with numbers from 0 to 100, without any drops.

# Potential solution
Locking mechanism for sheet tables. If another workflow is writing to the sheet, the execution should be paused until the lock is released, to prevent having race conditions.



Hopefully this clarifies the problem better.

**Comment by janober** [comment]
Ah OK, now I understand.
Yes, the way n8n is currently designed something like that can happen. Is a known issue and that will improve together with our push to make n8n scaleable. Then at least no executions should be lost but it would still be possible that the order gets messed up (because if it gets executed on different machines and one is faster than the other). A locking mechanism is currently not planned and would just make everything much more complicated esp. across different machines (which I think is currently simply not worth).

What you can try for now, is to tell n8n to execute everything in the main thread as documented here:
https://docs.n8n.io/reference/configuration.html#execute-in-same-process
by setting:
```bash
export EXECUTIONS_PROCESS=main
```

Like that it just uses one CPU but it does not create a new process for each workflow-execution which allows a much higher throughput and saves a lot of memory. It should then also execute everything in order (but also not guaranteed as it also depends on Google, do not think it is 100% sure that if 1 request gets made 1 ms before the other, the first one really gets executed first).

Hope that makes sense. We simply have to prioritize and can not address every single issue.
