### ISSUE TITLE
Bug? Tweets are truncated

### ISSUE THREAD

**Issue by fidelix** [n8n-io/n8n#1212]
Using the Twitter search function brings a truncated tweet with the "truncated" property set to true.

Is there an available workaround? Is this a bug?

**Comment by RicardoE105** [comment]
@fidelix It seems to be expected. According to the Twitter docs `truncate:true` means:

_Indicates whether the value of the text parameter was truncated, for example, as a result of a retweet exceeding the original Tweet text length limit of 140 characters. Truncated text will end in ellipsis, like this ... Since Twitter now rejects long Tweets vs truncating them, the large majority of Tweets will have this set to false . Note that while native retweets may have their toplevel text property shortened, the original text will be available under the retweeted_status object and the truncated parameter will be set to the value of the original status (in most cases, false )._

**Comment by janober** [comment]
@fidelix can we close this issue considering what @RicardoE105 posted?

**Comment by fidelix** [comment]
I guess, but the tweet is absolutely missing a bunch of text that can be seen in the twitter website or app. I couldn't find the whole data in the json.

**Comment by janober** [comment]
Ah yes sure it is missing but there is literally nothing we can do about that. Here is the documentation of the API endpoint n8n uses:
https://developer.twitter.com/en/docs/tweets/search/api-reference/get-search-tweets
There is no option to not return them truncated. So if you need that option you would have to talk with Twitter to add that option first, before we are able to implement it.
