### ISSUE TITLE
Test workflow button is not working (intermittently happens every 1 to 2 weeks)

### ISSUE THREAD

**Issue by BUNCH-Dev** [n8n-io/n8n#12152]
### Bug Description

When it happens, clicking the Test workflow button and triggering a webhook using a postman request will not work as expected (no webhook node is not triggered, the UI will not display the running n8n nodes (they should have green border)

### To Reproduce

1. Go to workflow
2. Trigger a webhook node
3. Assuming the intermittent issue is happening, the webhook will not be triggered and you will see this error:
{
    "code": 404,
    "message": "The requested webhook \"contract-creator\" is not registered.",
    "hint": "Click the 'Test workflow' button on the canvas, then try again. (In test mode, the webhook only works for one call after you click this button)"
}

### Expected behavior

1. The error **The requested webhook \"contract-creator\" is not registered** should not be seen.
2. The triggered elements should have green-border and is inspectable

### Operating System

cloud n8n

### n8n Version

1.70.4

### Node.js Version

cloud n8n

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @BUNCH-Dev,

We have created an internal ticket to look into this which we will be tracking as "N8N-7941"

**Comment by Joffcom** [comment]
Hey @BUNCH-Dev,

You mentioned you are running on n8n cloud, If this is our cloud service can you email help@n8n.io as this is more than likely an issue in the configuration rather than the node itself. They will also be able to create an internal bug ticket after checking your environments logs.

For now as this appears to be a Cloud support issue I am going to mark this as closed, If you are not using n8n cloud and hosting it yourself let me know and we can open this again.
