### ISSUE TITLE
Issue with mongo atlas connection

### ISSUE THREAD

**Issue by iqbaal77** [n8n-io/n8n#1276]
**Describe the bug**
Mongo atlas not connecting with n8n after working couple of hours found that there are three major fixed required as per my knowledge 
1) Mongo atlas URI should be  mongodb => "mongodb_srv" when start n8n (server crashing)
2)  If resolved above => Migrations not running properly when mongodb connected it crashing the server
3) If resolved above => If workflows are empty then again crashes the server 
4) Finally I have fixed it and may it should be pushed to the branch if not fixed by the team yet!

**To Reproduce**
1. Go to 'n8n root folder update db type to mongodb and atlas URI in .env file'
2. Click on 'just write n8n start'

**Expected behavior**
Mongodb should be connected only updated in .env file

**Environment (please complete the following information):**
 - OS: [win32x64]
 - n8n Version [0.98]
 - Node.js Version [ v15.4]

**Additional context**

**Comment by janober** [comment]
Sorry to hear that you have problems. In this case, we will however not be able not fix it. The reason is that Mongo support will be dropped very soon as documented here:
https://docs.n8n.io/reference/data/database.html#mongodb
So spending resources on fixing something we want to remove very soon anyway would not be a very good time investment. Hope that makes sense.
