### ISSUE TITLE
UI glitch - Trying to select multiple lines in Code Editor results in a close by accident

### ISSUE THREAD

**Issue by ixidion** [n8n-io/n8n#1353]
**Describe the bug**
The Code Editor closes too often by accident when marking multiples lines while holding the mouse button and releasing it outside the code editor.

**To Reproduce**
1. Create a node, e.g. FunctionItem
2. Click in the Code Editor and wait for popup to open.
3. type some lines
4. mark these lines with the mouse and still hold left mousebutton.
5. Leave with mouse button pressed the code window and release the button
6. Code Editor window closes

**Expected behavior**
Code window should stay open. Close should happen with either pressing the "X" or hitting 'ESC'.

**Environment (please complete the following information):**
 - OS: Debian 10 with Docker
 - n8n Version 0.101.0
 - Node.js Version 12.19

**Comment by janober** [comment]
Thanks a lot for reporting this.

I am actually OK with closing the editor in the case somebody clicks outside of it. The problem here is really that it also closes it on releasing the button, and that should not happen. Is esp. annoying when selecting code (as you mentioned). As I did not find a way to easily fix that specific behavior did I now deactivate close on click as you proposed. Will be released with the next version.

**Comment by janober** [comment]
Got released with n8n@0.103.1
