### ISSUE TITLE
Executions list only shows "Unknown" status

### ISSUE THREAD

**Issue by dploeger** [n8n-io/n8n#1591]
**Describe the bug**
The list of executions only shows the status "Unknown" and the tooltip says "The workflow execution is probably still running but it may have crashed and n8n cannot safely tell."

**To Reproduce**
1. Plan the execution of a workflow using a trigger
2. Wait until the execution has been run
3. Show the list of executions

**Expected behavior**
The list of executions show wether the workflow was run successfully.

**Environment (please complete the following information):**
 - OS: Docker Image
 - n8n Version 0.113.0
 - Node.js Version bundled with docker image

**Comment by krynble** [comment]
Hello @dploeger 

Sorry for the delay on responding to your issue.

Can you share the workflow you are using for this?

This `Unknown` status is a new flag for when n8n is running in queue mode with workflows that are started via `Execute Workflow` node.

In this case, n8n cannot safely tell if the workflow is correctly running or crashed and is a known issue, but should not be the case for all executions, running or not.

**Comment by dploeger** [comment]
The workflow [dev_to_to_Blog_and_Twitter.txt](https://github.com/n8n-io/n8n/files/6334016/dev_to_to_Blog_and_Twitter.txt) is run using a Trigger node.

Interestingly enough, a second workflow [New_Github_Repos_to_tweets.txt](https://github.com/n8n-io/n8n/files/6334017/New_Github_Repos_to_tweets.txt), that is also executed using this, shows the correct result instead of Unknown.

![image](https://user-images.githubusercontent.com/203453/115196955-ca350680-a0f0-11eb-9d08-ad5d9521356d.png)

**Comment by krynble** [comment]
Interesting findings @dploeger 

I have a few questions that can help us track the problem:

- Are you using queue mode?
- If you open the executions that failed what do you see? Are there errors?
- If you don't have any errors from the previous question, can you try enabling saving execution progress in the workflow settings so that n8n saves after each step taken. This allows us to understand if a specific node is having issues

**Comment by dploeger** [comment]
I need some clarification there.

* What's queue mode? 😄 
* The executions are note really failed, I guess. It's just undefined to n8n wether they got executed. When I click on the folder icon I get the workflow view without any more information.

![image](https://user-images.githubusercontent.com/203453/115201485-aa541180-a0f5-11eb-9e03-68967c2aa383.png)

* I've enabled saving the execution progress now. Will update after it has run again.

**Comment by krynble** [comment]
Sure =)

Queue mode is when you run n8n with workers. This is the case when you need n8n to scale further than a single machine.

I will assume this is not the case in your use as it would require a bit of set up =)

About the execution progress, this should help us understand how far n8n went executing the workflow.

If it crashes during the execution (let's say the computer runs out of memory and n8n process crashes) it will display as `Unknown`.

This is an intended behavior.

A few more questions:
- Is this workflow running for a long time? If so, the errors you are seeing are all new?
- How big is the data being handled by the nodes? In order to keep performance at maximum, n8n keeps a lot of information in memory. If n8n is running in a machine with low RAM, it might crash and display as `Unknown`
- Lastly, related to previous question, how much RAM does the machine running n8n have?

**Comment by dploeger** [comment]
Yes, I simply started n8n on a single machine from the Docker image, so I guess as well that queue mode isn't enabled.

* The workflow should only be running for a short period of time
* The biggest dataset is the output of [this rss feed](https://dev.to/feed/dploeger), which is not really much
* The machine has 12GB of RAM and only 6 of that are used

The save execution step setting worked, this is the result:

![image](https://user-images.githubusercontent.com/203453/115216993-53563880-a105-11eb-8a7b-cd7c123b237b.png)

That's a successful run I'd say, because it didn't have any posts to publish. The executions list still shows Unknown though.

**Comment by krynble** [comment]
hey @dploeger

Sorry for the late response. I could not reproduce this problem on my machine using the workflows you provided.

Tried the latest version and also 0.113.0 as you mentioned to be using with no success. It works just fine for me.

Can you try upgrading to the latest version? We've made a lot of improvements recently that can fix the issue you're having.

Please keep me posted.

**Comment by dploeger** [comment]
Updating didn't help. I will try to recreate the workflow that still has the "Unsuccesful" state.

**Comment by dploeger** [comment]
No. Downloaded the workflow, removed it, imported it again and activated it again. Still "Unknown" status for the trigger.

**Comment by janober** [comment]
Got released with n8n@0.120.0

**Comment by dploeger** [comment]
@janober Nope, same results. Please reopen.

**Comment by krynble** [comment]
Thank you for your feedback @dploeger 

I will continue investigating this issue and will keep you posted.

**Comment by dploeger** [comment]
@krynble  Thanks a lot. Tell me if I can be of any help.

**Comment by krynble** [comment]
Hey @dploeger can  you email me to omar @ n8n dot io?

I am investigating the issue and would love to collect some feedback from you.

Thanks again!

**Comment by dploeger** [comment]
Yay. After changing the encoding of my database (see #1905) everything works now. Thanks a lot! That was a hard one and you showed true dedication, @krynble ❤️

**Comment by krynble** [comment]
No problem @dploeger I am super glad we found the issue and fixed it =)

**Comment by janober** [comment]
Got released with n8n@0.125.0
