### ISSUE TITLE
Issue in mail-send operation with Dynamic Template Fields in Sendgrid node

### ISSUE THREAD

**Issue by LeoScant** [n8n-io/n8n#1649]
In Sendgrid node, when selecting the send-email operation with a Dynamic template if I specify more than one 'Dynamic Template Field' only the last one is passed to SandGrid and displayed in the email template and the others are ignored.

**Comment by janober** [comment]
When opening an issue please make sure to:
1. Use the predefined template instead of just deleting it
2. Look if there is already an existing issue or PR (open & closed)
3. Use the latest n8n version and make sure that the issue still exists in that version

Because of 1. I am not sure which n8n version you are using. But I assume you are using an old one as the reported issue got already fixed with this PR https://github.com/n8n-io/n8n/pull/1631 which got released with `n8n@0.115.0`

If the issue still exists also in that version please open a new issue. Thanks!
