### ISSUE TITLE
Execute Workflow (several times) from another workflow

### ISSUE THREAD

**Issue by lublak** [n8n-io/n8n#1764]
**Describe the bug**

Currently I start another workflow from one workflow (several times)
1. I get an Unknow in the Executionlist for the status.
2. it is then completely empty (i.e. when I open it via the folder icon) 
    `There was a problem initializing the workflow:
can't access property "resultData", e.workflowExecutionData.data is undefined`
3. ~furthermore, the sorting is not displayed correctly when this list is "automatically updated". When the workflow is started, it sometimes ends up somewhere in the middle and not at the top~ until it disappears again.
4. it gets stuck, also after restarting n8n it is displayed as unkown, not all workflows have been started. ~and wiggles back and forth in my execution list~.

Part of it may be fixed by this:

https://github.com/n8n-io/n8n/pull/1761

![grafik](https://user-images.githubusercontent.com/44057030/117646765-72883900-b18c-11eb-9893-d4ffd91395a4.png)

**To Reproduce**
1. Create 2 workflows
2. First workflow starts the second workflow (Currently 1000 times)
3. Start the first workflow manual

I assume that the 2nd workflow has a timeout.

**Expected behavior**

A stable process of the sub-workflow or show an error (timeout error?)

**Environment (please complete the following information):**
 - OS: Windows 10
 - n8n Version:  0.119.0 
 - Node.js Version: v14.15.1

**Additional context**

Currently very difficult to produce a simple example of this as it occurs in a more complex workflow.

**Comment by krynble** [comment]
Hi @lublak

Thanks for reporting this. This is a known an expected behavior when running n8n in scaled mode (when you set `EXECUTIONS_MODE` to `queue`).

The way workers initialize jobs makes n8n unable to exactly tell if the "subworkflow" executions are still running or crashed.

Question: if you reduce the times you call this to a low number, like 5. Does it work fine?

The expected behavior is to see executions as `Unknown` but after a while all of them should finish properly and change the status to `Success`.

Also regarding timeouts this is something we recently pushed an update on version 0.119 so in theory this should've been fixed too.

Lastly, can you please share the workflows that you used? That is greatly appreciated.

**Comment by janober** [comment]
@krynble did create a possible fix #1775

I will release that fix soon with the next version. Hopefully, that fixes the issue.

**Comment by janober** [comment]
Got released with n8n@0.120.0

Closed the issue for now. If it does not fix the issue please report back then we can open the issue again.
