### ISSUE TITLE
Create Credentials - Data too long for column "type" at row 1

### ISSUE THREAD

**Issue by arvigJustinBarber** [n8n-io/n8n#1766]
**Describe the bug**
When creating new credentials for "Google Firebase Realtime Database OAuth2 API" I get an error stating that the data for the type column is too long

**To Reproduce**
1. Go to credentials and click new
2. Select "Google Firebase Realtime Database OAuth2 API" as the Credential Type
3. Fill out the rest of form with test or personal credentials
4. Click create

**Expected behavior**
This should create the credential

**Environment (please complete the following information):**
 - OS: Alpine Linux -- Version 3.11.7
 - n8n Version 0.119.0
 - Node.js Version 14.15.5

**Additional context**
![image](https://user-images.githubusercontent.com/40208398/117697783-7d40cf00-b188-11eb-98c3-edd40ab0d595.png)

**Comment by krynble** [comment]
Hi @arvigJustinBarber 

Thank you for your report! What database system are you using? Unless otherwise changed, n8n uses SQLite.

We use the `text` field type to store credentials and it can hold up to 64kb of data, but we save the data as encrypted JSON so it might take a lot more space.

Thanks.

**Comment by krynble** [comment]
Hi @arvigJustinBarber

The field that is yielding errors is actually the `data` column.

We will be releasing an update but it implies in creating a new migration to update this field type on a next version.

If you change the field from `TEXT` to `MEDIUMTEXT` our migration will fail so you would have to update the `migrations` table manually (this shouldn't be hard to do) letting n8n know that the change was already made.

If you feel comfortable doing this (manually adding migrations in the future and changing field types) then feel free to apply the changes. Otherwise I would recommend waiting for the next version that should be released by the end of this week with this fix.

I should be creating a PR with this fix soon.

**Comment by janober** [comment]
Fix got merged and changed it to `VARCHAR(128)`. Will be released soon. Thanks for reporting.

**Comment by krynble** [comment]
Thanks for fixing that @janober I thought it was the same issue with the `data` field but in this case it relates to `type` as mentioned by @arvigJustinBarber. I am sorry about my misinterpretation.

**Comment by janober** [comment]
Got released with n8n@0.120.0
