### ISSUE TITLE
Export all workflow return No workflows found

### ISSUE THREAD

**Issue by dust63** [n8n-io/n8n#2088]
Using the latest image of n8n on docker.
I ran docker with the image. I created 2 workflows with 1 credential.
I connect a cli to the current docker image with docker desktop
Execute:
``` 
n8n export:workflow --all
```
response:
```
Error exporting workflows. See log messages for details.
No workflows found with specified filters.
```

**Environment:**
 - OS: docker image of n8n, Alpine Linux v3.11
 - n8n Version: 0.133.0
 - Node.js Version: 14.15.5
 - Database system: SQLite
 - Operation mode: own

**Comment by janober** [comment]
The guess the problem is that you do not connect with the correct user. n8n does start as user `node` but you then probably connect as user `root` (which is default`). It will so use a different user-folder (the one of the user root). As the root user did never run n8n, it will not find any workflows and so the above output is totally correct.

If you set the user to `node` like in the following example it will work as expected:
```bash
docker exec -it -u node myn8n n8n export:workflow --all
```
(example assumes the name of your docker container is `myn8n`):
