### ISSUE TITLE
Setting base url doesn't solve running in subdirectory (e.g. behing Nginx)

### ISSUE THREAD

**Issue by SmallhillCZ** [n8n-io/n8n#212]
**Describe the bug**
The Base URL setting described in https://docs.n8n.io/#/configuration does not support running the app in subdirectory behind reverse proxy. Static Vue files are not loaded as `<base>` href tag is not set.

**To Reproduce**
1. Run n8n with base url set to https://example.com/n8n
```sh
docker run -it --rm   --name n8n   -p 80:5678 -e "VUE_APP_URL_BASE_API=http://example.com/n8n" n8nio/n8n
```
2. Open http://example.com/n8n in browser
3. You see blank page

**Expected behavior**
n8n loads okay.

**Environment (please complete the following information):**
Using Docker
n8n 0.46.0

**Comment by janober** [comment]
Yes, `VUE_APP_URL_BASE_API` is not meant for that. It simply tells the frontend how it can reach the backend. 

I never tried to run it in a subfolder but can imagine that it will cause some issues. Here and maybe also in other parts of the application. The currently recommended way is to run n8n under its own domain/subdomain. Have no idea how much work it would be to run in a subfolder. It is honestly also right now not a priority at as I do not have many resources available, there are so many other things to do and running it on a subdomain is a viable alternative. Very sorry.

**Comment by janober** [comment]
Addition: I would also not call it a bug right now. Would say it is more of a "feature-request" which you can post here:
https://community.n8n.io/
If a lot of people are interested in it the priority on it will obviously change.

So close this issue for now.

**Comment by BhushanGit77** [comment]
@SmallhillCZ  I was also facing the similar issue.
I wanted to access n8n via browser on url: https://example.com/n8n. Setting VUE_APP_URL_BASE_API didn't work.

setup:
n8n container running locally on port 5678 behind reverse proxy. Reverse proxy accessible on port 443.

I tried following solution and it worked.

set env variable N8N_PATH= /n8n/
set env variable WEBHOOK_URL= [https://example.com:443/n8n](https://example.com/n8n)
set env variable N8N_PUSH_BACKEND=sse
On my reverse proxy side, I added logic to rewrite the path before sending to n8n, basically stripping away path prefix (ie. /n8n) so that requests at n8n arrive at n8n:5678 without path prefix.
eg. [https://example.com:443/n8n/abc](https://example.com/n8n/abc) -> http://example.com:5678/abc

With this approach things started working for me. I am able to open n8n on my browser using custom url.
