### ISSUE TITLE
when click duplicate workflow the webhook duplicated with same url  

### ISSUE THREAD

**Issue by voko3456** [n8n-io/n8n#2386]
when click duplicate workflow the webhook duplicated with same url  it sholud be create webhook with new url 

Error showing when i try to save duplicated workflow :

There was a problem and the workflow could not be activated:
SQLITE_CONSTRAINT: UNIQUE constraint failed: webhook_entity.webhookPath, webhook_entity.method

**Comment by BHesseldieck** [comment]
Hey @voko3456 

the behavior, as you are describing it, is intended, since a duplication creates an exact copy of the node. This is especially useful if you are working with route-parameters.

When you create a new webhook Node from the Node Selection Panel on the right, then you will also receive a new URL.
