### ISSUE TITLE
Xero only allows the first 100 contacts, I can't change the 'page'

### ISSUE THREAD

**Issue by ebecaf** [n8n-io/n8n#2391]
If I want the first 100 contacts, great, but if I want contacts 101-200, or 201-300, I can't specify that, why?

Also the Get All switch doesn't work, i just get:
`
{"message":"Request failed with status code 400","name":"Error","stack":"Error: Request failed with status code 400\n    at createError (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/n8n/node_modules/axios/lib/adapters/http.js:269:11)\n    at IncomingMessage.emit (events.js:327:22)\n    at IncomingMessage.EventEmitter.emit (domain.js:467:12)\n    at endReadableNT (internal/streams/readable.js:1327:12)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)"}
`

Xero has a huge API and lots of parameters for Get Contacts, is there a way to use them rather than creating a HTTP node?
https://developer.xero.com/documentation/api/accounting/contacts#get-contacts

Several other nodes have custom parameters, so that would be my preference if anyone is able to add that.

Thank you

**Comment by ivov** [comment]
Thank you for your report.

The `returnAll` error should be fixed by the PR.

Regarding the limit field, it has an [upper limit of `100`](https://github.com/n8n-io/n8n/blob/ebdd86a5f5f5c86d7b8647ada464dcc1bf45e0f1/packages/nodes-base/nodes/Xero/ContactDescription.ts#L455), so any higher value will become `100`. We will look into improving this UX in the future.

**Comment by janober** [comment]
Fix got released with `n8n@0.150.0`
