### ISSUE TITLE
Create Google Drive integration

### ISSUE THREAD

**Issue by janober** [n8n-io/n8n#24]
Create an integration for Google Drive similar to the Dropbox/NextCloud one.
https://developers.google.com/drive/

Dropbox and NextCloud-Nodes are a good reference and starting point:
https://github.com/n8n-io/n8n/blob/master/packages/nodes-base/nodes/Dropbox/Dropbox.node.ts
https://github.com/n8n-io/n8n/blob/master/packages/nodes-base/nodes/NextCloud/NextCloud.node.ts

**Comment by mscansian** [comment]
Does this include Google Forms? It one of the most common use cases I have nowadays (since I spend a lot of time automating workflows for people that can't code). Something like a form gets a new answer then a workflow starts running.

I'm quite new with the project. For what I've managed to understand I could do this using a trigger in the Google Sheets that the form saves the replies, but it would be nice to have a direct trigger.

**Comment by janober** [comment]
This issue was actually only planned for files. But agree that also Google Forms is important and creating Trigger node for it should not be to complicated.

You can request for integrations to be added here:
https://community.n8n.io/c/feature-requests/nodes

People can then upvote them. That makes it then easier for me to know what is important for people and what node. Created there actually already a request for TypeForm myself:
https://community.n8n.io/t/typeform-integration/24

You are right. You should be able to do that already by yourself with the Webhook-Node and then set the Webhook-URL in Google Forms yourself. In the end are all Trigger-Nodes also just Webhook-Nodes which additionally takes care of the Webhook registration and deletion (if the APIs support it). So simply makes it easier and more convenient.

**Comment by janober** [comment]
Close as integration got created.
