### ISSUE TITLE
bad dialog UX on mobile screens

### ISSUE THREAD

**Issue by tennox** [n8n-io/n8n#2545]
**Describe the bug**
I mean it's definitely not only dialog ux, but it's what annoyed me a lot, and seems like an easy fix:
Dialog width & closeability:

![Screenshot_20211209-211440__01](https://user-images.githubusercontent.com/2084639/145469644-37ea6cbe-30be-4570-9ac3-6fe445718e0d.jpg)
![Screenshot_20211209-211445__01](https://user-images.githubusercontent.com/2084639/145469250-6d49733a-7fe3-4d08-9df2-0c808a93085c.jpg)

**To Reproduce**
Open a dialog on mobile.
Firefox Android
Android 10
OnePlus 6T

**Expected behavior**
Include the close button in the header for example.

Also: detect screen size correctly (breaks a lot of views on mobile)

**Additional context:**
Might submit a PR myself soon.

**Comment by Joffcom** [comment]
Hey @tennox,

The n8n interface has not really been designed for mobile use so I would expect there to be some issues, It sounds like this would be part of a bigger feature request to fully support mobile devices.

Rather than tracking this as an issue it might be worth voting on the feature request here: https://community.n8n.io/t/mobile-friendly-editor/1845 so we can see how important this is to the community.

For now though as this is kind of expected I am going to mark this one as closed.
