### ISSUE TITLE
The paused nodes are crossed

### ISSUE THREAD

**Issue by artemdzyuba** [n8n-io/n8n#2578]
**Describe the bug**
When a node is paused, it is crossed with a line
![image](https://user-images.githubusercontent.com/20184727/146547918-e23787d6-e4d4-4a68-9a43-ab2226e7ab6f.png)

**Expected behavior**
The node should not be crossed, only greyed out

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu Linux 20.04]
 - n8n Version [e.g. 0.1520]

**Comment by BHesseldieck** [comment]
hey @artemdzyuba,

tl;dr: it is not a bug/issue that you are experiencing, but intended behavior

we changed the canvas design recently as you have recognized. On the connecting arrows you will now see how many items are passed from one node to the next. In order to clarify that this node is not consuming these items, but they get passed to the next, we decided to show it with the line that crosses through the node.

I want to thank you for the feedback and hope that my explanation shed some light on the thinking behind it.
