### ISSUE TITLE
Human-readable tunnel URL not saved after n8n restart

### ISSUE THREAD

**Issue by SurPaul** [n8n-io/n8n#2716]
**Describe the bug**
Please take a look at the screenshots.

**To Reproduce**
First run: `n8n start --tunnel` and restart.

First run | Restart
--- | ---
![image](https://user-images.githubusercontent.com/1708881/150635749-71443a20-573e-4309-a041-02281dce6645.png) | ![image](https://user-images.githubusercontent.com/1708881/150635787-1aabb01c-744c-47cf-9dbc-a649e86e4c26.png)

**Expected behavior**
The domain will remain the same as at the first run.

**Environment (please complete the following information):**
 - OS: Raspbian GNU/Linux 11 (bullseye) armv7l
 - n8n Version: 0.159.1
 - Node.js Version: v17.4.0
 - Database system: default
 - Operation mode: default

**Comment by Joffcom** [comment]
Hey @SurPaul,

This is something we are aware of but don't really track it as a bug as such, We know the tunnel changes and a new one is randomly generated when your instance connects because of this we don't tend to recommend using tunnel in a production environment (https://docs.n8n.io/getting-started/installation/#n8n-with-tunnel).

If you rely on the Tunnel it would be worth either looking into port forwarding and using your own domain or maybe trying what some other community members are doing and use ngrok (or another tunnel service) to get a URL https://community.n8n.io/t/n8n-desktop-custom-webhook-url-ngrok/9634.

Hopefully this helps.

**Comment by janober** [comment]
fyi and just to make it clear. That only happens if the connection with the tunnel service gets killed in a "not normal fashion". As then the tunnel-service somehow still thinks the connection is alive even though it is not. If n8n does get stopped normally, by  for example pressing "ctrl + c", it disconnects normally and free up that subdomain again. Meaning if n8n starts text next time the subdomain will be available to be used and so be consistent across multiple launches.

**Comment by SurPaul** [comment]
Thanks for answers. Right now I'm not using the tunnel service anymore. I was able to set up n8n on my own domain

**Comment by Joffcom** [comment]
That is good news, I am going to close this one out for now.

If you have not already done it don't forget to check out our [community forum](https://community.n8n.io) 👍
