### ISSUE TITLE
Cannot execute postgres node - unknown reason

### ISSUE THREAD

**Issue by mvhirsch** [n8n-io/n8n#276]
**Describe the bug**
I'm currently trying to connect to my postgres database and executing a simple SELECT-statement.
As a response the only hint is "Workflow execution process did crash for an unknown reason!". This is really unhelpful for debugging my root cause of this crash.

Is there a way to analyze my issue? Can I turn on some debug logs or similar?
I don't know what's wrong. I just tried the SQL-statement withing DataGrip, which is fine. I also re-checked my database credentials twice.

**To Reproduce**
1. Create new workflow
2. Configure a postgres node
3. Run postgres node

**Expected behavior**
Seeing my data, which I just selected.

**Environment (please complete the following information):**
 - docker: n8nio/n8n:0.51.0

**Additional context**

**Comment by mvhirsch** [comment]
Just found out there is an IP restriction between my networks and n8n's. Looks like my fault, sorry for that.

But being curious: is there still a way to help debugging such issues?

**Comment by janober** [comment]
Great to hear that you found the issue.

About debugging. Normally n8n forward the error it receives. But in your case, the whole process seems to crash for some reason (which should never happen). So n8n does not receive any information it could display to you. It would maybe be interesting to check why it crashes in your case and then fixing that so that the actual error can be returned like it is supposed to.
