### ISSUE TITLE
Double click doesn't work on touchscreen

### ISSUE THREAD

**Issue by immanuelfodor** [n8n-io/n8n#277]
**Describe the bug**
The UI is not optimized for touchscreen usage but somewhat usable, however, double click/tap doesn't work at all, it's impossible to open a node settings dialog for quick edit on the go (e.g., via phone). 

**To Reproduce**
1. Go to any workflow
2. Zoom out with the magnifier +/- buttons until you see the nodes
3. Pinch zoom in to a node to be able to tap on it
4. One tap works (sometimes, depends on tap position on the node), the grey buttons appear around the node, but double tap is not recognized at all. Impossible to edit the node. 

**Expected behavior**
You can open the node settings dialog with double tap or please provide a settings button (e.g., grey cog icon). 

**Environment (please complete the following information):**
 - OS: Docker
 - n8n Version: latest DockerHub build
 - Node.js Version: latest DockerHub build

**Additional context**
- It would be great to have better overall support for touch devices, this is a fun project to play with any time you have a bit of time to spend. 
- It's also impossible to connect two nodes on a touchscreen, but editing is more important for quick settings adjustments.

**Comment by janober** [comment]
Yes, I am honestly not surprised. Did never test it on a touch-device and would not have expected that it would work. Are therefor not even sure if I would call it currently a bug or a feature request. I have also not the slightest idea how much work it would be to make everything properly work for touch-devices. I agree that it would be great if it would work but is definitely not a priority right now because there are so many other things to do and so few resources.

For now, I would probably treat it more like a feature request and so advise you to also post it in the forum:
https://community.n8n.io/
If many members upvote it, it would become obviously then also more of a priority.

**Comment by immanuelfodor** [comment]
Fair enough, here is the newly created community thread: https://community.n8n.io/t/double-click-doesnt-work-on-touchscreen-general-touchscreen-optimization/747

**Comment by janober** [comment]
@immanuelfodor Thanks a lot!
