### ISSUE TITLE
Limit HubSpot credentials OAuth scopes

### ISSUE THREAD

**Issue by carlin-q-scott** [n8n-io/n8n#2782]
**Describe the bug**
I cannot select the scopes I want to request from HubSpot, and as a result, my connection is rejected because n8n is requesting all the scopes.

**To Reproduce**
1. Credentials
2. New
3. Hubspot OAuth2 API
4. Enter my Client ID and Secret key from HubSpot
5. Specify scopes???
6. Click "Connect my account"
7. Accept app installation in new HubSpot window
8. Get rejected because:
   > Couldn’t complete the connection
The app developer doesn't have permissions to request the set of scopes. Please contact the app developer.

**Expected behavior**
HubSpot should have accepted the app installation / account connection

**Environment (please complete the following information):**
 - OS: Windows 10 build 19043.1466
 - n8n Version 1.2.0.0 (Windows App)

**Additional context**
I only have the oauth and contacts scopes enabled for my HubSpot app.

**Comment by Joffcom** [comment]
Hey @carlin-q-scott,

I have just done a test using the Hubspot API with the below scopes and it has allowed me to connect, It did prompt that the app wanted more but still allowed me to add the private app to my Hubspot account.

![image](https://user-images.githubusercontent.com/4688521/152966188-c3074947-1b58-45e1-891f-add3d2546d81.png)

What type of Hubspot app are you using is it a developer app or a private app?

**Comment by carlin-q-scott** [comment]
@Joffcom I am using a private app I believe; it's unlisted but can be installed in any account. I created it before November 2021, so I guess [what they're talking about here on the n8n forum applies](https://community.n8n.io/t/hubspot-developer-account-insufficient-scopes-were-provided-please-contact-the-app-developer/8671/18).

This is my scopes config panel, which doesn't allow selecting read/write individually:
![image](https://user-images.githubusercontent.com/2521644/153102708-ba81f9a7-58ff-4f55-9c28-e32407eca070.png)

**Comment by carlin-q-scott** [comment]
The HubSpot docs have this interesting statement:
> Please note: in addition to the standard scopes in the table below, some HubSpot APIs have support for granular scopes (e.g., crm.objects.contacts.read). Any endpoint that supports granular scopes will list the corresponding standard scope as a Legacy Scope, but unless otherwise noted, you can still use legacy scopes in your requests.
https://developers.hubspot.com/docs/api/working-with-oauth#scopes

Is the n8n code requesting all scopes as optional? Maybe it can request both the legacy and more granular scopes.

**Comment by Joffcom** [comment]
Hi @carlin-q-scott,

Looking at the scopes for the HubSpot credentials we don't request all the scopes but we also don't set them as optional although when making my app yesterday I was able to link it up with just a limited set but I appear to be on the newer scope setting so that post would apply.

It looks like the best option here would be to create a feature request to allow for scopes to be manually inputted by the user that should then solve the issue.

I have created a feature request for this here: https://community.n8n.io/t/hubspot-allow-manual-selection-of-scopes/11282 so we can track the amount of requests / demand for this.

As you are using the Desktop version of n8n it is a bit tricky to provide a quick fix that you could use, One thing you could try is to make another developer account which would give you the newer permissions although it isn't ideal.

**Comment by carlin-q-scott** [comment]
I switched to self hosted, so I'm open to ideas. I'm guessing I can change the code as I suggested locally?

**Comment by Joffcom** [comment]
Hey @carlin-q-scott,

Yeah that is an option so depending on how you are running it you would need to make a fork of the project, Change the code then either build out a new docker image using the provided templates or start it up with npm.

**Comment by Joffcom** [comment]
Hey @carlin-q-scott,

As we have the feature request open to track the votes on this one I am going to mark this issue as closed and we can keep an eye on the request to work out if there are more people that are after this sort of thing.
