### ISSUE TITLE
Can we n8n-core and n8n-workflow in an angular project?

### ISSUE THREAD

**Issue by Chinna2405** [n8n-io/n8n#288]
Hi,

Can we use the node packages n8n-core and n8n-workflow in an angular project ?
Please give us a detailed description of that packages how can we use or import that in an angular project.

Thanks in advance.

**Comment by janober** [comment]
Very sorry but have no experience with Angular and it is currently sadly no priority to make the modules independently usable as there are so many more pressing issues. For that reason is there also no documentation in any way.

Additionally are GitHub issues, like defined in the template, only for bugs. All questions should be posted to the community forum. So close this issue for that reason.
