### ISSUE TITLE
Better authentication with service providers

### ISSUE THREAD

**Issue by mscansian** [n8n-io/n8n#30]
From what I could understand, all of the credentials need to be manually created and inserted by the user on the CREDENTIALS menu.

Do you guys have any plan to implement an end user OAuth2 for some of them? For instance, instead of manually creating API keys to Asana with would be much better if I just have a button to click "Login with Asana" and provide the required permissions as per the OAuth2 flow.

**Comment by janober** [comment]
Ah yes, that is also planned in the futre. But did not do it yet for two reasons:

  1. Lack of time. Currently have to concentrate on what delivers the "biggest bang for the buck" and having more integrations is so more important at the current stage.
  2. The even more important reason. Having an OAuth2 auth in place really just makes sense for many users. Currently, there is only a self-hosted version and there is no user management. That means "normally" only one user has to authenticate. And so creating an Access-Token is normally at least as simple as creating and adding the tokens which are needed for OAuth2. So would right now be a lot of work without much of an advantage.

**Comment by mscansian** [comment]
1. That's what I thought. Wish I could help you guys with this, but unfortunately my Javascript skills are not that good (I'm a Python/Go developer for living). For now I will just stay with integrations (specially AWS, which I use a lot and are not that difficult to implement).
2. I disagree. If you think about Github it's easy to go to the console and create an API Key, but with some other providers this is a PITA. Even with a single user, having an OAuth2 button would help speed up things when using the software.

A little bit of threadjacking: What about the Commons Clause in the Apache license? For what I understand this kind of license is more suitable for open source, non-commercial projects that don't want anyone freebooting on their work or for profit companies that just provide the source free of charge but without accepting contributions back ('cause they don't need to).
I see that you guys are forming a company behind the n8n project. As much as I would like to contribute, I wouldn't want people from profiting on my free (as in beer) work. I don't know if you have considered, but maybe a more liberal (everyone can use for commercial purposes) or a more restrictive (no commercial use at all) license would be better suited for the project. The current one doesn't seem fair to individual contributors like me. Maybe something in the line of Nginx and [Nginx Plus](https://www.nginx.com/solutions/web-mobile-acceleration/) which are different versions of the same project would be more fair.

**Comment by janober** [comment]
2. Yes if there would only a button that would work I agree. But that this button works also access tokens would be needed (because also OAuth needs them) and so I would have to publish mine on Github. And if I do not want to do that, people have to add their own ones which means we would be again exactly where we started.

About the license. I already started to write something about that in the FAQ, will add it soon. 
But the short version is. I want that everybody (no matter if private or company) can use n8n totally free. I do not want people to make money with it directly (charging users) as they are normally not the ones helping the project. Are however open when people approach me (and already opened it to one who did). My goal is to earn money with the project to further develop it which I am sure will be best for the project.
Because in the end is probably 80% of the code still written by the team behind a project and the more money there is the bigger the team.

But think your comment is quite interesting. Because you say you do not want other people to profit from your free work but people/companies also do that without the Commons Clause. The only difference is that with the Commons Clause it limits it to people behind the project (which care about the project and invest a substantial amount of time) rather than a random company that simply wants to make money, does not care about it and helps it even less.

But sure I can understand if you do not want to contribute. Nobody has to. You can use n8n no matter what. Anyhow, I believe everything is always a giving and taking. And I personally think it is not the most insane way to think that: "When I use a project (somebody else did create and let me and everybody else use for free). One I actually use, which is helpful for me and saves me a lot of time, that giving back either financially or in time (by contributing code) is just fair."

**Comment by mscansian** [comment]
2. You're right. I forgot that for local app you also need to create a client KEY and SECRET :man_facepalming: 

@janober It makes sense, please include that in the FAQ. Surely more people will have the same question. Only a point to consider is that the Common Clause limits consulting/support and this restricts somebody for automating workflows for someone else. This might hurt the project in the long run (even Redis Labs moved out of the Commons Clause license because of this reason).
Yeah, I know I'm nitpicking on this, but license are easier to be discussed when the project is still small :)

**Comment by janober** [comment]
@mscansian Great to hear! Yes, I did anticipate questions about the license. Especially once I post the project next week on Hackernews and ProductHunt. I was thinking about the license for a long time. It was no easy decision. But I think for now it is the best. I wanted to be upfront about it and not having issues like other companies had when they changed their license later. I thought I can give people any time additional rights but I never want to take any away later. Would not feel right.
Yes, the consulting/support thing is also something I do not like about the license. But I am not a lawyer and so did not want to "write" an own one. So people can simply contact me if they want to do that. They can then tell me what they want to do and I can then give them "officially" the right to do it. So everybody is "protected".

**Comment by janober** [comment]
@mscansian Did now hurry to get the FAQ up asap. You can find them here:
https://docs.n8n.io/#/faq?id=license

**Comment by Stvad** [comment]
I think a significant improvement here would be to provide/require a howto + preferably a one-stop link for obtaining the relevant credentials for each integration, so user won't have to figure it out on it's own for each service.

**Comment by janober** [comment]
@Stvad Yes, you are totally right! That is one thing that is on my to-do list for months. Never got around to do it though. I should probably try to at least create one asap that can serve as an example that maybe other people can help out and create similar ones for other services.

**Comment by Stvad** [comment]
@janober An example would be a great start :)

**Comment by Stvad** [comment]
@mscansian I think one option for you to have more control regarding licensing as contributor is to create the nodes as separate packages (from what I understand the current architecture allows for that).

**Comment by sutidor** [comment]
It has been created.
see https://community.n8n.io/t/node-oauth2-api-wip/189/17

**Comment by RicardoE105** [comment]
For those interested. OAuth2 support is currently on beta stage and can be tested on this docker image https://hub.docker.com/layers/n8nio/n8n/0.67.3-oauth-beta/images/sha256-bd4c2632f5c5fc883fe31975059ab86439b29c9483632fd500a650f67e7761e0?context=explore
