### ISSUE TITLE
Notion node - Get operation missing

### ISSUE THREAD

**Issue by ThomasAlbrt** [n8n-io/n8n#3041]
**Describe the bug**
The `Get` operation for the `Page` resource for the `Notion` node is unavailable on some accounts.

**To Reproduce**
1. Create a Notion node.
2. Select the `Page` resource.
3. In the operation dropdown, `Get` operation is missing.

**Expected behavior**
Get operation should appear according to the [doc](https://n8n.io/integrations/n8n-nodes-base.notion).

**Additional context**
I teach a course on n8n and most of my students don't have the `Get` operation on their account. What's weird is that I have it on my account.

**Comment by Joffcom** [comment]
Hey @ThomasAlbrt,

Thanks for reporting this one, I just checked my local n8n install and I don't have the Get operation for the Page resource, It looks like for the v2 node it doesn't include it. In your install if you add a new Notion node does that also include the Get operation?

**Comment by ThomasAlbrt** [comment]
On my side I still have it.

I was able to copy the node json and send it to my students so they can proceed with the exercice.

**Comment by Joffcom** [comment]
Hey @ThomasAlbrt,

Are you running an older version of n8n maybe? I have just checked the code for the node and it looks like we moved it so the operation is now under Database Page > Get. In theory on your install assuming it is later than 0.157.0 if you added a new Notion node rather than doing a copy of the existing node you would get the newer options.

I will get a ticket created to have the notion documentation updated as it also uses the older Operation names, If you are happy I think we can mark this one as closed.

**Comment by ThomasAlbrt** [comment]
Indeed I didn't notice that I had to update n8n myself while being on n8n cloud.
I thought it was automatic + the documentation got me confused because it still showed the `Get` operation.

If the operation itself is still available with another label it's fine :)

Thanks !

**Comment by Joffcom** [comment]
Fantastic I will get this one closed 👍 have a good weekend.
