### ISSUE TITLE
Switch buttons on webhook URL mode are both toggled

### ISSUE THREAD

**Issue by laurent-lemke** [n8n-io/n8n#3135]
**Describe the bug**
When we configure the "trigger webhook" node, setting an expression and switching either to production (or test if we were already in production) leads to toggle both buttons

**To Reproduce**
Really easy
1. Add a "trigger webhook" node
2. Click on 'add expression', and enter a real expression (not a litteral). For example just put `{{}}` (or a real expression if you want such as `{{$env.MY_PRETTY_ENV_VAR}}`)
3. Apply the expression, then press on the switch button "production URL" 

<img width="897" alt="Capture d’écran 2022-04-13 à 17 51 16" src="https://user-images.githubusercontent.com/32649054/163221632-61e3b71c-67b2-4cc9-9ebe-d529a72a2b39.png">

N.B: Notice also that the label containing the webhook URL still has the previous value

**Expected behavior**
I was confused since I was not sure if I was still in test or in production.

**Environment (please complete the following information):**
 - OS: macOS and FF
 - n8n Version latest
 - Node.js Version 14.x
 - Database system don't care but postgres
 - Operation mode own

**Additional context**

**Comment by Joffcom** [comment]
Hey @AilurusFulgenz,

That is a good find, It looks like it only happens if the Expression can't be resolved so if you used something that can show a result it works like `{{$parameter["authentication"]}}` all is good.

The other problem here would be if you were to use an env option as we only resolve those on execution (I think) you wouldn't be able to copy the value anyway as it wouldn't exist so we may need to change that process for cases like this.
