### ISSUE TITLE
In view-execution mode, when executed multiple times, nodes parameter window shows only parameters of the first execution

### ISSUE THREAD

**Issue by rafalkrupinski** [n8n-io/n8n#3210]
**Describe the bug**
I have a HTTP Request node that is executed multiple times in a loop, and its parameters are changed in that loop.

1. Set: prepare parameters for the first execution
2. HTTP Request: make a request
3. extract cursor link and set it as parameter for the next call
4. if there's cursor link present, go to [2]

When in design or run view mode, I can't see parameter values in the node details view for the next executions, it only shows values for the first run.

**To Reproduce**
1. Run flow
5. open 'Get items' node
6. Select 'Data of execution' other than 1
7. See error - parameters of the first execution

**Expected behavior**
See the parameters as they were at that particular execution

**Environment (please complete the following information):**
 - n8n Version: 0.170.0

**Additional context**
[Workflow.json.gz](https://github.com/n8n-io/n8n/files/8570030/Workflow.json.gz)

**Comment by Joffcom** [comment]
Hey @rafalkrupinski,

This is one of those things that we are aware of but don't currently see it as a bug it is more of a feature request. We track these on our community forum which can be found here: https://community.n8n.io

I am going to mark this one as closed for now and I will open a new feature request on the forum for you later today so that we can track popularity.
