### ISSUE TITLE
nocodb change method from put to patch

### ISSUE THREAD

**Issue by cadcoin27** [n8n-io/n8n#3476]
https://github.com/n8n-io/n8n/blob/b36c290d78a1b108c8daabf133b54007a7993124/packages/nodes-base/nodes/NocoDB/NocoDB.node.ts#L301

**Comment by cadcoin27** [comment]
nocodb Operation "Update" always return unknow error because they use "PATCH" method not "PUT"

**Comment by Joffcom** [comment]
Hey @cadcoin27,

What version of NocoDB are you using? This is one of those issues where the API changed and our current node doesn't fully support  newer versions of NocoDB. The good news is we do have a PR in that will fix this issue, I am currenlty running through the review on it so it should be available soon.

**Comment by zblesk** [comment]
Hello @Joffcom , any news on this one?

**Comment by Joffcom** [comment]
Hey @zblesk,

We released an update to the node that works with the newer API version, is that working for you? You can select the API version under the nodes settings.

I do have another case opened where update isn't working but I suspect it could be down to the node version.

**Comment by zblesk** [comment]
Hey @Joffcom, thanks for pinging me. I updated the docker container; N8n now reports version 0.197.1. 

The behavior is the same - no error reported, no data changed in the DB. 
I also ran a `docker-compose logs -f --tail 300`, but nothing shows up in the log when I invoke the action. 

Just to double-check, since the documentation seems lacking: I prepared the update by entering the column's name as I see it in the UI. Is that correct? (Column name here is `Comment`.)
 
![image](https://user-images.githubusercontent.com/4245227/195018575-ec167ec0-3352-4a6d-bf62-2c39d9b0f3be.png)

As an aside on a marginally related note: the [docs](https://docs.n8n.io/integrations/builtin/credentials/nocodb/) for the NocoDB connector have a dead link to "Enable API Access" and they instruct me to set the "API Token". Nowhere in the UI is there an API Token, only a "User Token".
I have later found that I can set the User token in NocoDB's connector settings, but have to set the API token directly in the update node. 
I've tried using both, with the same results. 

My settings look like this: 

![image](https://user-images.githubusercontent.com/4245227/195021239-d2d7ad4c-c4f8-4e60-a7e4-9c59190c83a7.png)

**Comment by Joffcom** [comment]
Hey @cadcoin27,

I forgot to mark this one as closed when we released the update to the NocoDB node last year, If you use the updated node and set the API version to 0.90 onwards it will use `PATCH` instead of `PUT` which was used for the older NocoDB versions.
