### ISSUE TITLE
Termux Failed to start after installation

### ISSUE THREAD

**Issue by michaellw** [n8n-io/n8n#3603]
**Describe the bug**
Installed with the command "npm install n8n -g" in Termux, but eventually the service did not start

**To Reproduce**
1. Install binutils
2. Install nodejs
3. npm install n8n -g
4. n8n

Initializing n8n process
n8n ready on 0.0.0.0, port 5678
Version: 0.183.0
/data/data/com.termux/files/usr/lib/node_modules/n8n/dist/src/Server.js:1774
                    model: cpus[0].model,
                                   ^

TypeError: Cannot read properties of undefined (reading 'model')
    at Server.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/n8n/dist/src/Server.js:1774:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Environment (please complete the following information):**
 - OS: [Termux 0.118.0.118]
 - n8n Version [0.183.0]
 - Node.js Version [18.4.0]
 - Database system [SQLite]
 - Operation mode [own]

**Comment by Joffcom** [comment]
Hey @michaellw,

Is this an android device you are trying to install on?

It looks like the emulation is not able to retrieve the CPU model which could be a limitation of Termux and there may not be anything we can do.

It may be worth checking out community support forum to see if any other users have had success using Termux.

**Comment by michaellw** [comment]
> Hey @michaellw,
> 
> Is this an android device you are trying to install on?
> 
> It looks like the emulation is not able to retrieve the CPU model which could be a limitation of Termux and there may not be anything we can do.
> 
> It may be worth checking out community support forum to see if any other users have had success using Termux. 

@Joffcom Yes, Android 11, I will try to look into it a bit more, thank you!

**Comment by raonigabriel** [comment]
I had exactly the same issue. 

@Joffcom , I  I wonder: why is the CPU model required for?
I mean; even if Termux returns null / "empty",a simple elvis operator could replace that to "unknown".

**Comment by Joffcom** [comment]
Hey @raonigabriel,

The CPU Model, Count and Speed is used as part of the diagnostic information if there are any issues, My main concern with using Termux / a mobile to run n8n is some of the features might not work which is why we don't officially support it.

There are some users who have managed to get it working, One of them posted a guide up on the support forum about it which you can find here: https://community.n8n.io/t/installation-issue-on-termux/10475/18

Looking at this one now I am not sure this is a bug as it is expected although we could potentially work around it but it would require a core change.

I think the best bet for this would be to maybe create a feature request to provide support for Android / Termux.

**Comment by raonigabriel** [comment]
Understood,  thanks for the detailed answer!
I will take a look on that guide and try to get a PR.

**Comment by Joffcom** [comment]
Hi There,

I am going to mark this one as closed as we don't currently support Termux directly, It could be that in the future this might change but running n8n on a mobile device while cool is not a recommended option.
