### ISSUE TITLE
Re-running failed executions does not re-execute workflow

### ISSUE THREAD

**Issue by roemhildtg** [n8n-io/n8n#365]
**Describe the bug**
When I try to re-run failed executions using an updated workflow, the job immediately fails and does not re-run. 

Details:

I created a new docker container - and my encryption key got reset. Therefore all my credentials stopped working and existing workflows now have some failures in steps like "Email".

After re-creating the new credentials though - I'm still seeing the same error message, even though I have updated the old workflow iwth the new credentials. 

**To Reproduce**

1. Create a workflow with a credential stored, like email
2. Remove the credential from the store (this breaks the workflow)
3. Try running it (it will fail in the email step)
4. Repair the workflow by adding a new credential and re-configuring email to use the new credential
5. Try to re-run the Error’ed out execution. It still tries to use the old workflow, I cannot get it to use the new one.

**Expected behavior**

The workflow should re-run with the updated workflow item. 

**Environment (please complete the following information):**
 - OS: Amazon Ec2 Linux x64
 - n8n Version Docker:latest

**Additional context**

![example](https://user-images.githubusercontent.com/5471079/76534577-ac09cb00-6447-11ea-8847-4e3bc9dba200.gif)

**Comment by janober** [comment]
I can sadly not reproduce this. 

Have problems with step 3 (Try running it). That is simply not possible for me as n8n recognizes (as it should) that the credentials with this name do not exist and so so does not allow me to execute the workflow.

**Comment by roemhildtg** [comment]
Hmm, that makes sense. 

Maybe try doing something like just providing the wrong email credentials. Then have it run from web hook. Then try and re-run it after fixing/updating the credentials.

**Comment by janober** [comment]
I could not reproduce the issue.

It seems like that when I tested, I actually always just did with changing the nodes after the one that did fail instead of actually with the node that did fail itself. Now doing that, I could identify my mistake and fix it. 

Additionally, did I find and fix another issue which resulted in the original error staying behind after the re-run. Because of it, did it display the node that did fail as being executed twice.

I will release the new version with the fix today.

Thanks a lot for making me aware of this issue @roemhildtg!

**Comment by janober** [comment]
Got released with n8n@0.56.0

**Comment by roemhildtg** [comment]
Yep - this fixed the issue! Thanks so much!

**Comment by janober** [comment]
Great to hear that everything is fine now. Have fun!
