### ISSUE TITLE
Cannot save flow with pinned data

### ISSUE THREAD

**Issue by zgrummedical** [n8n-io/n8n#4002]
**Describe the bug**
Cannot save the flow after pinning data.

**To Reproduce**

1. Run http request node
2. Click on pin data
3. Try to save
Problem saving workflow

Request failed with status code 403

**Expected behavior**
Ability to save

**Environment (please complete the following information):**

- OS: Ubuntu 22.04 LTS
- n8n Version  0.193.2
- Database system SQLite 
- Operation mode own

**Additional context**
Running with docker-compose

**Comment by Joffcom** [comment]
Hey @zgrummedical,

I have just given this a go and I am not able to reproduce it, Did you connect to a certain website in the HTTP Request node before hitting pin data or just add the http request node then hit the pin data icon and press save?

Was this working on a previous version of n8n you were running or is this a new install and if using a reverse proxy or something like Cloudflare have you tried connecting directly to the containers IP / port to see if the issue is still there?

**Comment by zgrummedical** [comment]
I tried reproduce the issue in a local instance and it runs as expected there.

The problem seems to happen when using the instance that's running with a cloudflare tunnel.

**Comment by Joffcom** [comment]
Hey @zgrummedical,

That sounds like it may not be something we have any control over, When it goes through Cloudflare are you using the proxy option or is it set to just DNS?

I am not sure what Cloudflare is doing but it could be that it is caching something which is resulting in the failed request.

**Comment by zgrummedical** [comment]
It is using the proxy option.

**Comment by Joffcom** [comment]
That could be it then, sometimes it does some odd caching that can get in the way.

Going through cloudflare for your webhooks will be fine it is just the UI that can sometimes have issues but that is not unique to n8n.

**Comment by zgrummedical** [comment]
Found the issue!

Thank you for pointing me in the right direction with cloudflare. There was a security rule blocking the requests. My assumption is that when attempting to save the request with pinned data it saw some code in there and triggered a false positive.
