### ISSUE TITLE
Error in file packages/nodes-base/nodes/Box/Box.node.ts causing Box node to fail with error "responseData.push is not a function"

### ISSUE THREAD

**Issue by jjboardman** [n8n-io/n8n#4140]
**Describe the bug**
Believe there is an error in [packages/nodes-base/nodes/Box/Box.node.ts] file line: 535 causing Box node to fail on folder creation (and possibly others?) on v0.193.0+.
The error n8n outputs is responseData.push is not a function. I believe responseData.push(...executionData); should be returnData.push(...executionData); if it is supposed to be there at all.

**To Reproduce**
Update to v0.193.0+ and attempt to create a folder using the box node.

**Expected behavior**
For there to be no error thrown .

**Environment:**
- OS: Ubuntu 22.04
- n8n Version 0.193.0+
- Node.js Version 14.16.0
- Database system Postgres
- Operation mode queue

**Comment by Joffcom** [comment]
Hey @jjboardman,

Thanks for reporting this one, I will take a look shortly 👍🏻

**Comment by Joffcom** [comment]
Hey @jjboardman,

I managed to reproduce the issue and have fixed it in #4147, It looks like while the node is throwing an error it is still working in the background. As a temporary solution until the fix is released you could use the continue on error option or ideally downgrade to 0.192.x.

Thanks again for reporting this one.
