### ISSUE TITLE
Investigate increasing developer productivity with pull requests environments

### ISSUE THREAD

**Issue by waveywaves** [n8n-io/n8n#4296]
I would like to make life easier for existing and new n8n contributors including maintainers by implementing [Uffizzi](https://uffizzi.com/) previews. 
Disclaimer: I work on Uffizzi
Uffizzi is a Open Source full stack previews engine and is free for n8n. This will provide newcomers with previews of their PRs in the cloud, allowing them iterate faster, without having to first set up a complete development environment themselves.

TODO:

- [ ] Intial POC

**Comment by Joffcom** [comment]
Hey @waveywaves,

I have asked the question internally to see if this is something we would be interested, Personally I don't see what I would gain from using a service like Uffizzi over just running a couple of npm commands locally to check out the changes.

I don't think we technically fall under the free tier either as we are not an Open Source project.

**Comment by waveywaves** [comment]
> I have asked the question internally to see if this is something we would be interested, Personally I don't see what I would gain from using a service like Uffizzi over just running a couple of npm commands locally to check out the changes.

Hi @Joffcom, thank you for the questions :)
You would be able to better review PRs by checking if the individual components of n8n deployment are working well together at the PR stage itself. It makes it easier for the contributor as well to see how their changes reflect directly against the code in the repo.  

Before you run any npm commands you would have a preview readily available for you from where you can test your APIs/frontend even. Is there a particular way you review PRs locally ? What would you want in a preview environment to help better your PR review workflow ?

**Comment by Joffcom** [comment]
Hey @waveywaves,

Our license can be found here: https://github.com/n8n-io/n8n/blob/master/LICENSE.md while our source is available and we accept PRs it is not an OSI approved license which is why don't generally refer to ourselves as being Open Source.

When I am reviewing a PR the first step is to check the code which is normally easier locally in a text editor, From there it is a case of running it locally just to make sure the change actually works.

I am of course just one person and there is a team of us so while this wouldn't be for me it could be that someone else finds it useful. I will follow up internally to see if anyone else had any thoughts.

**Comment by waveywaves** [comment]
@Joffcom I just checked the License, we can support n8n for free for sure. 

> From there it is a case of running it locally just to make sure the change actually works.

In an event when you are not able to run the code locally or just want to run the change first, you can use Uffizzi

**Comment by Joffcom** [comment]
Hey @waveywaves,

We have had a chat about this internally and at the moment this isn't something that we feel is needed for our project, If this changes we will get in touch.

**Comment by waveywaves** [comment]
@Joffcom I understand. Thanks for letting me know.
