### ISSUE TITLE
Error `TypeError: Cannot read properties of undefined (reading 'model')` while starting n8n

### ISSUE THREAD

**Issue by Z0LDevs-varnion** [n8n-io/n8n#4355]
**Describe the bug**
Error `TypeError: Cannot read properties of undefined (reading 'model')`  while starting n8n process on terminal after fresh install
 `~ $ n8n start`
`Initializing n8n process`
`UserSettings were generated and saved to: /data/data/com.termux/files/home/.n8n/config`
`Migrations in progress, please do NOT stop the process.`
`Migrations finished.`
`query is slow: INSERT INTO "migrations"("timestamp", "name") VALUES (?, ?) -- PARAMETERS: [1588102412422,"InitialMigration1588102412422"]`
`execution time: 35178`
`Migrations finished.`
`n8n ready on 101.127.154.22, port 5678`
`Version: 0.198.2`
`/data/data/com.termux/files/usr/lib/node_modules/n8n/dist/src/Server.js:1087`
`                    model: cpus[0].model,`
`                                   ^`

`TypeError: Cannot read properties of undefined (reading 'model')`
`    at Server.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/n8n/dist/src/Server.js:1087:36)`
`    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

**To Reproduce**
installing n8n using [This tutorial](https://community.n8n.io/t/installation-issue-on-termux/10475/18)

**Expected behavior**
n8n get up and running

**Environment (please complete the following information):**

OS : Android 11
n8n Version : 0.198.2
Node.js Version : v16.17.1
Database system : ?
Operation mode : own
**Additional context**
Tried running and installing on termux before and its running,after upgrading n8n,it was unable to install so i reinstall the termux app and reinstall it using tutorial on [here](https://community.n8n.io/t/installation-issue-on-termux/10475/18) it was failed

**Comment by Joffcom** [comment]
Hi @Z0LDevs-varnion,

We have seen a few issues with Termux pop up, The issue here is because Termux doesn't return a value for the CPU model. Officially we don't support Termux as it will likely lead to other issues once installed. We do have an open issue already for this one though and it looks like the end result was for a feature request to be created as this isn't a bug with n8n.

You can find the original issue here which is still open for now here: https://github.com/n8n-io/n8n/issues/3603

For now I am going to mark this as closed.
