### ISSUE TITLE
When Called by Another  Workflow Trigger don't wait for the data

### ISSUE THREAD

**Issue by luizeof** [n8n-io/n8n#4402]
**Describe the bug**

The  When Called by Another  Workflow Trigger  don't wait for the data

**To Reproduce**

- Add an When Called by Another  Workflow Trigger
- Press Execute
- Workflow Stop

See inaction: https://www.loom.com/share/faa312d47bb44206a134cc8118857713

**Expected behavior**

Wait until the other workflow sends data to the trigger

**Environment (please complete the following information):**

- OS: [e.g. Ubuntu Linux 18.04]
- n8n Version [e.g. 0.119.0]
- Node.js Version [e.g. 14.16.0]
- Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed]
- Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `own`]

**Additional context**

**Comment by Joffcom** [comment]
Hey @luizeof,

Thanks for reporting this one 👍🏻 , I have taken a look at the node and it looks to be working as intended. It is basically the start node with a new name so that the older start node can be removed and replaced with something more meaningful.

We have created an internal feature request for this one which we will consider for a future release, For now as this is not a bug I will mark this one as closed. When / If we change the functionality of the node I will let know you.
