### ISSUE TITLE
Parameter parsing between HTTP Requests

### ISSUE THREAD

**Issue by carlskii** [n8n-io/n8n#443]
**Work flow is configure like this**

Start -> HTTP Request 1 -> HTTP Request 2 -> Function 1 -> HTTP Request 3

* HTTP Request 1 gets an API Key that can be referenced and passed as a header value to HTTP Request 2
 * HTTP Request 2 gets data from an API 
 * Function 1 reformats and extracts/splits data returned from HTTP Request 2 and passes it to HTTP Request 3
 * HTTP Request 3 essentially iterates the list provided by Function 1 and calls another API to get more information

**The problem** 

HTTP Request 3 needs to use the same API key as used by HTTP Request 2. It works fine with HTTP Request 2, however it does not appear to be passed to HTTP Request 3 and the request fails. If I manually define the API key within HTTP Request 3 it works OK. The UI allows me to define an expression and the expression result reflects the correct value. However, when I run the workflow,  HTTP Request 3 is failing because the API key is not there. 

**Environment (please complete the following information):**
- OS Mac OS 10.15.3
- n8n Version 0.59.0
 - Node.js Version v13.9.0

**Comment by janober** [comment]
Can you please create a simple example workflow making requests to something like https://requestbin.com/ that I can run it myself and can see what is going on. Thanks!

**Comment by carlskii** [comment]
Here you go, this actually works against the API, I'm trying to use. 

Interestingly, if the API returns a single item, it works as expected. However. if the API returns multiple items the API doesn't get passed for the iteration. 

I've provided two flows, one that returns a single item and one that returns multiple items so you can see where it goes wrong. 

[example.json.txt](https://github.com/n8n-io/n8n/files/4420559/example.json.txt)

**Comment by carlskii** [comment]
Hi any updates on this? Is it me or is it a bug?

**Comment by janober** [comment]
The reason is that an expression always gets the data of the same item. 

So lets assume:
 - Node 1 has: 1 item
 - Node 2 has: 2 items

If you then have an expression on a parameter on Node 2 the following will happen:
 - Expression on 1. item: works fine as Node 1 also has an item with index "0"
 - Expression on 2. item: will fail as Node 1 has only one item and so no item with index "1"

To solve that you have to define that you always want to get the data of item 0 like this:
{{$item(0).$node["Authenticate with API"].json["APIKey"]}}

Documentation here:
https://docs.n8n.io/#/nodes?id=method-itemindex

In the future please open a Github issue only if you are 100% sure that it is a bug and else post it to the forum here:
https://community.n8n.io

Only if people always do that, can we be sure that if other people have the same problem they find the answer easily because all of them are on the same website. Thanks!

**Comment by carlskii** [comment]
Thanks for this - this did the trick. Will ask in the community next time round.
