### ISSUE TITLE
AWS Ses Custom verification email

### ISSUE THREAD

**Issue by xemorytr** [n8n-io/n8n#4482]
Hello
Ubuntu 22 os
Docker Image: n8nio/n8n:0.200.1-debian
Credential for AWS
AWS account
Resource
Custom Verification Email
Operation
Send
Email
aaaa@aaaa.com
Template Name
1

Problem in node ‘AWS SES‘
UNKNOWN ERROR - check the detailed error for more information

NodeApiError: UNKNOWN ERROR - check the detailed error for more information
    at Object.awsApiRequest (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Aws/SES/GenericFunctions.js:24:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.awsApiRequestSOAP (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Aws/SES/GenericFunctions.js:39:22)
    at async Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Aws/SES/AwsSes.node.js:859:40)
    at async Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/src/Workflow.js:658:28)
    at async /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/src/WorkflowExecute.js:562:53

**Comment by Joffcom** [comment]
Hey @xemorytr,

Can you complete the template when opening issues it helps us collect the information we may need to work out what is going on.

For this one does the template you are using exist?

**Comment by xemorytr** [comment]
Hello yes template 
template name: mailv i use

**Comment by Joffcom** [comment]
Hey @xemorytr,

When you say "first sound" what do you mean? It sounds like maybe during a recent change to the AWS nodes we have caused an issue with SES. Can you try using 0.188 and see if that has the same problem?

**Comment by xemorytr** [comment]
0.188  working version.

**Comment by Joffcom** [comment]
Hey @xemorytr,

What do you mean by Windows setup file? You mentioned about using the docker version that is the case right and you are not using n8n Desktop?

**Comment by xemorytr** [comment]
> Hey @xemorytr,
> 
> Windows kurulum dosyası ile ne demek istiyorsunuz? Doğru olan docker sürümünü kullanmaktan bahsettiniz ve n8n Desktop kullanmıyor musunuz?

yes i am using docker.
some of my friends have people who use windows for sound.
that's why I asked.

**Comment by ZackWard** [comment]
I am also running into this issue. I'm not sure if you need another data point, but here is my info:

**Describe the bug**
The AWS SES node returns an unknown error when attempting to send email.

**To Reproduce**
Steps to reproduce the behavior:

1. Create an AWS SES node and provide valid credentials (test connection works)
2. Configure node to send a test email
3. Trigger the node

**Actual behavior**
The execution fails with an Unknown Error and the following stack trace:
```
NodeApiError: UNKNOWN ERROR - check the detailed error for more information
    at Object.awsApiRequest (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Aws/SES/GenericFunctions.js:24:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.awsApiRequestSOAP (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Aws/SES/GenericFunctions.js:39:22)
    at async Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/Aws/SES/AwsSes.node.js:934:40)
    at async Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/src/Workflow.js:658:28)
    at async /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/src/WorkflowExecute.js:562:53
```

**Expected behavior**
A test email should be sent

**Environment (please complete the following information):**

- OS: Docker on Raspberry Pi 4b (8Gb) Host
- Image: n8nio/n8n:latest (43f78529c533)
- Database system:  SQLite
- Operation mode: own

**Additional context**
![image](https://user-images.githubusercontent.com/3154622/199227181-b4d88918-165c-47f9-9572-3c98547f6234.png)

**Comment by Joffcom** [comment]
Hey @ZackWard & @xemorytr,

I have been going through some older issues and I was not able to reproduce this today on the latest version, I have a feeling this was resolved a few versions back so for now I am going to mark this one as closed.

If you are still seeing this one let me know and we can open it again.

**Comment by ZackWard** [comment]
@Joffcom Thank you for following up! I ended up switching to the SMTP node, and that allowed me to debug the issue. I'm leaving this here in case anybody else runs into the same problem.

The real issue was that my SES account was sandboxed, and I needed to approve the recipient's email address. The specific error message wasn't obvious when using the SES node.

**Comment by Joffcom** [comment]
Hey @ZackWard,

That is interesting to know, I know we are working on returning better error messages and most of the time will return the error from the service but I think there are some older nodes that still need a bit of gentle nudging on the backend :)
