### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by barart** [n8n-io/n8n#4530]
Hello i installed n8n from the docker image, nothing special or custom configs, the first time i was able to login with the user/password that i put when running the container (-e), my session was opened until now that i restarted my browser, now when i try to login to my n8n container it ask me for a email and password, i dont have email because the variable is a user/password combination not a email, so im not unable to login, if i put my user on the mail field it says "Must be a valid email"

I only have one workflow and it is running fine, i already restarted and recreated the container but it ask me for the email/password combination instead user/password; when recreating my container my workflow still there and still running...

How can i change the login to user/password or how can i login?

**Comment by Joffcom** [comment]
Hey @barart,

We use Github to track bugs with n8n at first glance this doesn't look a bug, would you be able to created a post on our community support forum which can be found here: https://community.n8n.io

As a starting point there have been a few posts with similar incidents like this one: https://community.n8n.io/t/issue-with-self-hosted-login/19116 and https://community.n8n.io/t/remove-account-owner-and-deactivate-user-management/13226 these may help solve the problem you are facing.

For now I will close this and if it turns out to be a bug we can open it again.
