### ISSUE TITLE
431 Request Header Fields Too Large

### ISSUE THREAD

**Issue by ddezoysa** [n8n-io/n8n#466]
**Describe the bug**
431 Request Header Fields Too Large comes with larger headers.

**To Reproduce**
1. HTTP Request Node
2. Provide any API details with a header value larger than 8 Kb. 
3. Execute node
4. Check the error in the browser inspect element.
Behavior is the same for other Nodes as well.

**Expected behavior**
API calls should work for larger header sizes as well.

**Environment (please complete the following information):**
 - OS: MacOS 10.14.6
 - n8n Version: 0.60.0
 - Node.js Version: v13.12.0

**Additional context**
The default maximum header size in Node.js is 8KB. Permanently increasing the header size to the maximum or making it configurable with an environment variable is required to get this fixed.

**Comment by janober** [comment]
Yes, sending headers which are larger than 8kb will cause problems right now with n8n because of the default Node.js limit.

As you said, is it possible to overwrite it. That can be done with `--max-http-header-size=X` as described here:
https://nodejs.org/api/cli.html#cli_max_http_header_size_size

Sadly do I not see a way how n8n could take care of that as the Node.js process is already running at that point and can so not be changed anymore. The only way would be, to start another Node.js process which then runs n8n with that parameter. This, however, does not really make sense for me, as I think that the 8kb limit is reasonable and this is an edge-case. Larger headers will normally not be needed and if they are, people can simply start n8n like this:

```bash
/bin/node --max-http-header-size=65536 bin/n8n start
``` 

So the workaround is also reasonably simple in my eyes. So I think no change is needed in the n8n code.

**Comment by janober** [comment]
Did not hear back so close this issue as it seems to be fixed via the above workaround.
