### ISSUE TITLE
fix(Switch Node): Equal Numbers Issue

### ISSUE THREAD

**Issue by valentina98** [n8n-io/n8n#4698]
**Describe the bug**
The N8N Switch node rules (equal condition) does not work with numbers.

**To Reproduce**
Execute the following nodes:
```
{
  "nodes": [
    {
      "parameters": {
        "dataType": "string",
        "value1": 20,
        "rules": {
          "rules": [
            {
              "value2": "20"
            }
          ]
        },
        "fallbackOutput": 3
      },
      "id": "35904128-e6a6-4330-aaab-c55cab8e9216",
      "name": "Switch1",
      "type": "n8n-nodes-base.switch",
      "typeVersion": 1,
      "position": [
        560,
        260
      ]
    },
    {
      "parameters": {
        "value1": 20,
        "rules": {
          "rules": [
            {
              "operation": "equal",
              "value2": "20"
            }
          ]
        },
        "fallbackOutput": 3
      },
      "id": "1c6e6777-043d-4dce-9071-61d33d834ebb",
      "name": "Switch2",
      "type": "n8n-nodes-base.switch",
      "typeVersion": 1,
      "position": [
        560,
        400
      ]
    }
  ],
  "connections": {}
}
```
In both of them the item goes to the fallback output.

**Expected behavior**
The item should go to output 0 because the numbers are equal.

**Environment:**

- OS: Ubuntu Linux 22.04
- n8n Version: 0.198.2
- Node.js Version: v14.19.1
- Database system: default SQLite
- Operation mode: default  own

**Comment by janober** [comment]
I just tested the Switch-Node and it works fine for me. At least if I configure the node in the UI. Because in this case, the correct parameter do get displayed (in your above example for "String" will display a parameter for strings and if set to number one for number.

How did you create the above example? For me, it looks like it has been edited in a text-editor.

Generally, is the above example working as expected. Because `20` (number) !== `"20"` (string) and the correct output is so `3`, the configured fallback one.

The same could also happen if expressions are used, they also simply return what they return, no matter the parameter type. There it is also important to make sure the correct value does get returned. So if set to compare numbers, a `parseInt()`/`parseFloat()` is required or when working with strings a `.toString()`.

I hope that helps.
