### ISSUE TITLE
Google calendar trigger not creating events for email invitations after accepting (with yes or maybe)

### ISSUE THREAD

**Issue by wally2511** [n8n-io/n8n#4826]
**Describe the bug**
The trigger does not detect events that have been created from email invitations. For example someone emails me a calendar invite for an appointment in 2 days. If I respond with "Yes" or "Maybe" the trigger node does not detect the event in "created" mode. Update does work.

**To Reproduce**

1. Set up the trigger to detect created events.
2. From an external account, send a calendar invite
3. Accept the calendar invite in gmail

**Expected behavior**
When the event is confirmed with "Yes" or "Maybe" the trigger detects the newly created event on the clanedar

**Environment (please complete the following information):**

- OS: Ubuntu Linux 22.04
- n8n Version 0.205.0
- Node.js Version Unsure - using docker image
- Database system SQLite
- Operation mode Own

**Additional context**
The update trigger catches the event

**Comment by Joffcom** [comment]
Hey @wally2511 

I will take a look into this one today and see what our trigger is doing.

**Comment by Joffcom** [comment]
Hey @wally2511,

Bit of a delay on this one, It looks like we use the date the event was created and check to see if it was after the last run of the trigger.

I suspect with invited events the created date is the date the sender created it rather than when it was created in your calendar, Out of interest does Event Modified work for you?

**Comment by Joffcom** [comment]
Closing for now pending feedback, Will re-open if this is still an issue.
