### ISSUE TITLE
Code Node Editor missing features/shortcuts since update from Function Node

### ISSUE THREAD

**Issue by MichaelNussbaumerGOWEST** [n8n-io/n8n#4844]
**Describe the bug**
Since Interface Update, the Editor for Function/Code Node is missing some features/shortcuts. (Selecting of multiple lines Alt + Shift + Drag Mouse, Ctrl + # to comment out code)

**To Reproduce**

1. Add a Code Node
2. Try to use the Shortcuts from above

**Expected behavior**
The shortcuts should work as they did before

**Environment (please complete the following information):**

- OS: [Rocky Linux 8]
- n8n Version [0.202.0]
- Node.js Version [e.g. 16.17.0]
- Database system [MySQL 8]
- Operation mode [`queue`]

**Comment by Joffcom** [comment]
Hey @MichaelNussbaumerGOWEST,

We generally try to use Github to track bugs, In this case we are aware of the changes to the code node and while they are not ideal for all users we are aware of the functionality that is missing.

Part of this change is down to the change in editor being used which allows us to do more and offer better features in the future. For now this is intentional and something that we consider to be a feature request, There are a few requests on our support forum and this one seems to be the closest if you want to give it a vote: https://community.n8n.io/t/recommendation-allow-full-screen-ish-editor-for-the-code-node/18850

For now I am going to mark this as closed, Thanks for taking the time to report this though.
