### ISSUE TITLE
Polling for triggers

### ISSUE THREAD

**Issue by mscansian** [n8n-io/n8n#49]
As far as I'm aware all triggers are just implementations of a webhook. This is the best option when available, but it's not always there.

One use case is an AWS SQS queue. Amazon doesn't provide anything other than a polling endpoint to receive new messages. It would bee necessary to have a trigger that automatically polls data every X time.

PS: The polling interval should be configured by the user (better yet per-node configuration). As I starting point, I think a default of 60 seconds should be enough (Zapier and other alternatives have an even slower poll interval).

Relevant docs: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SQS.html#receiveMessage-property

**Comment by janober** [comment]
Just to make sure that I understand you correctly. I guess you do not mean in the workflow, I guess you mean for the node-code itself?

If that is what you mean I am not sure if we need "global code" for that as it could be implemented specifically for each need as the code is very simple. In the end it would just be a simple version of the Interval node:
https://github.com/n8n-io/n8n/blob/master/packages/nodes-base/nodes/Interval.node.ts

So a setTimeout which runs all X seconds some code (like make http request) and send calls to the `emit()` function if data got found. For me it seems like writing an additional layer on top of that would make it even more complicated rather than easier. As everybody understands directly the setTimeout code when they see it but would have to go in the docs first to understand the additional layer.

Or do you mean that it would some special functionality like that for example calls do not overlap and similar?

**Comment by janober** [comment]
Just wanted to update that some generic trigger code got implemented and does get used by those nodes:
https://github.com/n8n-io/n8n/blob/master/packages/nodes-base/nodes/Clockify/ClockifyTrigger.node.ts
https://github.com/n8n-io/n8n/blob/master/packages/nodes-base/nodes/Toggl/TogglTrigger.node.ts

Closing this issue. If there is anything else needed simply open another issue.
