### ISSUE TITLE
How to reset password?

### ISSUE THREAD

**Issue by boramalper** [n8n-io/n8n#51]
I cannot find any link on the login screen.

**Comment by mjhea0** [comment]
I ran into the same issue.

**Comment by janober** [comment]
First sorry for your problems! Yes, the n8n.io website is still kind of Alpha. Feels like a large second project when I already do not have enough time to properly support the other one (n8n itself). But still wanted to have something in place where people can inform themselves about nodes and find and share workflows. That is also really what the whole website is about. So do you want to do that? Share a workflow with the community? If not there is no need for you right now to signup/login anyway as it is the only thing that can be done right now.

I assume you come from Hackernews and you thought you signed up for a hosted solution. That is understandable. Because of a very heated discussion about the term "Open Source" did the moderators decided to rename the post from "Open Source Workflow automation alternative to Zapier" to just "Workflow automation alternative to Zapier" which now sounded like a SaaS like Zapier is instead of what n8n actually is.

There is currently no hosted solution yet. But if you are interested you can leave your email on the following page to get informed as soon as it is available:
https://n8n.io/hosting

**Comment by boramalper** [comment]
I understand that, thank you for the project and your swift response. =)

**Comment by janober** [comment]
@boramalper You are welcome! Even though I am suprisied about the "swift response" comment. Felt actually bad because it took me very long as I have a mountain of emails, messages and other stuff to go through. But I take what I can get ;-)

**Comment by boramalper** [comment]
24 hours is pretty swift in my opinion, especially for a FOSS project. =)

**Comment by janober** [comment]
@boramalper Happy to hear! Still to try to be faster in the future.

Btw. because the Commons Clause is attached I think FOSS would not be the correct term. Here some information about the license:
https://docs.n8n.io/#/faq?id=license
