### ISSUE TITLE
MySql docker compose config

### ISSUE THREAD

**Issue by HosseinAsadi** [n8n-io/n8n#5110]
I was trying to deploy n8n with docker compose and mysql config (with run docker compose up), I keep getting "MySql password......(using password 'yes')" error. By checking the different modes (way), I found that there is a problem with the $ symbol(sign) in the password and it is impossible to log in to mysql.
Therefore, I said it can be useful to raise it as an issue

**Comment by Joffcom** [comment]
Hey @HosseinAsadi,

This doesn't sound like a bug with n8n and is likely down to the $ character not being escaped in the compose file. Did you try using `$$` to escape it?

You can read a bit more into this here: https://docs.docker.com/compose/compose-file/compose-file-v2/#variable-substitution

For now I will mark this one as closed and if it turns out to be something else we can open it again.
