### ISSUE TITLE
Sending mail failed by SMTP with self-signed certs. Need an option to turn tls checking on/off.

### ISSUE THREAD

**Issue by leopku** [n8n-io/n8n#5136]
**Describe the bug**
Sending mail by SMTP with self-signed certs throw:
```
Problem in node 'Send Email'

140220352338304:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:331:
```

**To Reproduce**

1. Go to 'Credentials'
2. Click on 'Add Credential'
3. Fill SMTP infos with self-signed certs
4. Select this credential in a `Send Email` node
5. Click 'Execute Node'

**Expected behavior**
Mail should be sent.

Maybe it's better add an option about something like 'tls check' to keep on/off.

**Environment (please complete the following information):**

- OS: Docker
- n8n Version: 0.209.4
- Node.js Version [e.g. 16.17.0]
- Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed]
- Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `own`]

**Additional context**
Maybe it's better add an option about something like 'tls check' to keep on/off.

**Comment by Joffcom** [comment]
Hey @leopku 

Under the options for the node there is an option for `Ignore SSL Issues` have you already tried this?

The message you are seeing though is possibly not because of the self signed certificate and could be where the mail server is expecting TLS not SSL, under the credential try changing the `SSL/TLS` option.

**Comment by leopku** [comment]
@Joffcom 

The SMTP setting works correct by msmtp(a command line kit like sendmail). Below is `.msmtprc`(mention: turned tls check off).

```
defaults
port 587
tls on
tls_starttls on

account maddy
host 10.0.1.232
tls_certcheck off   // <-  MUST turn off tls check here
from no-reply@xxx.xxx
auth on
user no-reply@xxx.xxx
password 12345678

account default: maddy
```

Almost same thing n8n not working. Below is `SMTP account` settings in :

User: `no-reply@xxx.xxx`
Password: 12345678
Host: 10.0.1.232
Port: 587
SSL/TLS: on

Below is `Send Mail` node settings:

Credential for SMTP:  SMTP Account
From Email: no-reply@xxx.xxx
To Email: leo@xxx.xxx
Subject: test
Text: test
Options:
  Ignore SSL Issues: on

Error occurred when node excuted:

ERROR: 140504474052992:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:331:

**Comment by Joffcom** [comment]
Hey @leopku,

We are still seeing the message about the wrong SSL Version, Can you set SSL/TLS to Off you currently have it On which will try and use SSL rather than TLS. Your credential should look something like this...

![image](https://user-images.githubusercontent.com/4688521/212296015-ee41e254-e1e8-4035-8dfe-7471329071a5.png)

The label on the credential is very misleading, I am going to get a quick request in to have that changed now.

**Comment by leopku** [comment]
Amazing. It works.
Thanks a lot!
