### ISSUE TITLE
Typeform Trigger not work

### ISSUE THREAD

**Issue by essivision** [n8n-io/n8n#518]
**Describe the bug**
Typeform Trigger  not work

**To Reproduce**
1. Create new Typeform Trigger
2. Set API credential and set specific form
3. Click on executive workflow
4. Fill form in Typeform as test
5. Then return to n8n board and see (1) badge top of  Typeform Trigger icon
6. Double click on Typeform Trigger icon and see null data
```
[
   {
     -
   }
]
```

**Expected behavior**
I want to get form data that I filled in Typeform 

**Environment (please complete the following information):**
 - OS: Windows 10 build 17134
 - n8n Version 0.63.0
 - Node.js Version v10.15.2

**Additional context**
What should I do? I need help

Thanks for helping

**Comment by janober** [comment]
Normally please only post here if you are 99.9% sure it is a bug. If not post in the forum.

Anyway, is your n8n web accessible? So did you for example start it with a tunnel?

**Comment by essivision** [comment]
Is your n8n web accessible? yes
I wanna to implement this example [Typeform to Google Sheet and Slack or Email](https://www.youtube.com/watch?v=rn3-d4IiW44&list=PLlET0GsrLUL5HKJk1rb7t32sAs_iAlpZe&index=1)

**Comment by janober** [comment]
I tested it just again. Works perfectly.

Are you filling the published version of the form or the preview-one? Because only the published one will call webhooks.

**Comment by essivision** [comment]
Yes, I publish it.
this is [form1](https://essivision.typeform.com/to/SpeY2I)
and this is my n8n that [publish in web](http://178.63.232.182:5678/workflow)

Please check it with my n8n. I set API in this app and ready for your test

**Comment by janober** [comment]
It seems that your n8n instance is not correctly configured.
 1. You are right. It is web-accessible but it is not configured to know about how it is reachable. You can see that when you click on `Webhook URLs`. There it says still `http://localhost:5678/webhook-test/1/typeform%20trigger/webhook`. Meaning it creates triggers for `localhost` which can not work. Either `N8N_HOST` or  `WEBHOOK_TUNNEL_URL` has to be set.
2. Even if the issue from 1 would be fixed it would probably still not work as you have it not configured to work via a domain you rather run it via its IP address which will not work for 90% of the webhooks.
3. Has to do with 2. As you do not have a proper domain setup it is served via HTTP and not HTTPs which will also not work for the most webhooks.

You should also never let your n8n run without authentication. I guess it is running like that only temporary to give easy access for us right now but then you should still have authentication activated and send the password in private via email. Because like this it is very easy for people to take over your server and do all kinds of stuff with it.

**Comment by essivision** [comment]
Thanks for answer
How to configure `N8N_HOST` and `WEBHOOK_TUNNEL_URL`? In setup process in windows (CLI) doesn't this configuration

**Comment by janober** [comment]
I do not use windows but if I google it I get the following result:
https://superuser.com/questions/79612/setting-and-getting-windows-environment-variables-from-the-command-prompt

Anyway, you have to fix all 3 problems for it to work. And setting these variables is your smallest problem. You have to make sure to have a domain name and a valid SSL certificate and then configure everything accordingly. 

So what you need to do is:
 1. Get a Linux Server (virtual or not, but probably yes as they are much cheaper). If not find somebody who knows how to configure everything on windows one.
 2. Get a domain-name.
 3. Setting everything up correctly like described here: https://docs.n8n.io/#/server-setup (the guide is for Linux)
