### ISSUE TITLE
docker pull error

### ISSUE THREAD

**Issue by wifiuk** [n8n-io/n8n#5263]
Recently ive started getting

Could not do a head request for "n8nio/n8n:latest", falling back to regular pull.
Reason: registry responded to head request with "404 Not Found", auth: "not present"

**Comment by Joffcom** [comment]
Hey @wifiuk 

What command are you running to pull the image? The latest tag appears to be on Dockerhub are you maybe using it with authentication?

**Comment by wifiuk** [comment]
I use watchtower to update them when they are available, I am using authentication.

**Comment by Joffcom** [comment]
Hey @wifiuk,

That is useful to know, I have done a quick search and this isn't directly an issue with n8n but will cause issues for anyone using Watchtower (https://github.com/containrrr/watchtower/discussions/1529).

I would suggest manually pulling the update for now which will work as expected and I will have have a chat with @netroy to see what we can do on our side about this.

**Comment by Joffcom** [comment]
Hey @wifiuk,

I was having a look through the Watchtower issue again and it looks like it might just be a warning and not an error caused by some rate limiting. It looks like you can disable this warning which would just hide the problem another potential solution is to change how often Watchtower checks for new images.

We are planning on releasing images in a different location from the next release so you could try that instead and see if it improves anything.

**Comment by wifiuk** [comment]
Thanks for the update
