### ISSUE TITLE
executions continually running

### ISSUE THREAD

**Issue by craigz** [n8n-io/n8n#5561]
**Describe the bug**
All executions are running since upgrading to 0.217.0. Every job run is displaying as still running.  Clicking on `View` only displays a message stating `Execution is running. It will show here once finished.` 

In the main `Executions` view the most recent job for example displays `Running for 1.012s`. Clicking `View` while showing the still running message, in the sidebar shows that its been running for `4:49m` and counting upwards. Looking down the list, sure enough each job shows a longer and longer running time until the first job run after update which has now been running for `217:00m` and counting. Jobs from prior to the upgrade all show as completed within just under or just over 1 second depending. 

**To Reproduce**

1. upgraded to the `latest` n8n (0.217.0)
2. launch n8n
3. view `All executions`

**Expected behavior**
Jobs to queue, launch & complete.

**Environment (please complete the following information):**

- OS: [Docker Deskop for Mac 4.16.2 (95914)]
- n8n Version [e.g 0.217.0]
- Database system [SQLite]
- Operation mode [own]

**Comment by csuermann** [comment]
Thanks for reporting this. We'll look into it right away and are tracking it internally as N8N-6206

**Comment by krynble** [comment]
@pluusla and @craigz thanks for the report.

Could you provide us with some more details?

- What type of trigger are you using?
- Is this happening to all executions or just a few specific workflows?

**Comment by Joffcom** [comment]
Hey @pluusla,

If you create a new workflow does it have the same issue? Are you also able to share one of the workflows that has the issue?

**Comment by flipswitchingmonkey** [comment]
Hi @craigz and @pluusla, I'm trying to reproduce the issue here as well...

- any chance you remember which version you were running before the upgrade?
- do you feel comfortable looking into the database directly? if so, it would be very interesting to find out what's in the row for one of the forever-running executions (id = executionId) - in particular the 'status' column.

**Comment by flipswitchingmonkey** [comment]
No worries, I think we figured out the issue and you don't have to do anything really. As a first note: your executions ran successfully despite of what the status is saying, so there is no need to worry.

A small patch should also fix them retroactively. The issue here had to do with an.... interesting conflagration of the combination of node and a race condition between hooks. Basically something that was supposed to set the status correctly was overtaken by something that did not.

We will have a fix for you soon!

**Comment by krynble** [comment]
Hello! Following the words of @flipswitchingmonkey we have built a custom docker image you can use. It's tagged `n8n-6206-executions-continually-running`

You can pull it running `docker pull n8nio/n8n:n8n-6206-executions-continually-running` or run it using the same syntax.

Could you please try this image and let us know if it works fine?

**Comment by krynble** [comment]
Hey good news. As said @flipswitchingmonkey we have built a custom docker image that you can use.

We'd like to get your feedback before releasing a new version.

You can find the tag [here](https://hub.docker.com/layers/n8nio/n8n/n8n-6206-executions-continually-running/images/sha256-fa47841468951cdd6c5a944c87314c48481482439f72f519da4d7e6c086ea4ac?context=explore) or pull it using `docker pull n8nio/n8n:n8n-6206-executions-continually-running`

This image is not available in arm64 so I'm afraid newer macs won't be able to run it.

**Comment by flipswitchingmonkey** [comment]
The arm64 image should now be available as well

**Comment by krynble** [comment]
Yes you are correct @craigz the workflows do run as normal and they're not running forever. It's just the database status that was inconsistent, but the runtime was fine.

So although annoying there was no impact to productivity or the execution itself.

The images are being built and should be available any time soon, CI is running :)

I'll be closing this issue but if you find any remaining problems please do reopen.
