### ISSUE TITLE
Salesforce API is hardcoded to old version (39.0 vs current 57.0)

### ISSUE THREAD

**Issue by idanblich** [n8n-io/n8n#5578]
Salesforce Connector is hardCoded to old version (39.0 vs current 57.0)
Using the latest Salesforce API version is important for a few reasons:
1. Security
2. Performance
3. Compatibility
4. Access to new features

Expected behavior : 
Add option to set the credentials api ver else use the current one (set once user create the credentials) 

Here is the location in the code need to be adjust 

![image](https://user-images.githubusercontent.com/1132993/221684911-339e97f9-1db0-4403-b686-f156aaa0d26a.png)

https://github.com/n8n-io/n8n/blob/b03e358a1283df0a446616d8ff6cc3d0ef067af7/packages/nodes-base/nodes/Salesforce/GenericFunctions.ts#L28

**Comment by Joffcom** [comment]
Hey @idanblich 

Is the node currently broken for you or is this more of a feature request?

**Comment by idanblich** [comment]
kind of broken ..i cannot retrieve database schema (tables and fields) from higher API ver.
I'll be happy to try provide PR if you will point me to some docs / reference in other connectors

**Comment by Joffcom** [comment]
Hey @idanblich 

Are you able to prove an example workflow or an error that you get when it is broken?

I do have an internal ticket open to update the Salesforce API this year because 31 - 40 are likely to hit end of life next year.

We try to keep GitHub issues for breaking issues only with feature requests going through the community support forum to help with prioritising issues.

If you wanted to pop in a PR to do this we have a contributing guide available which can be found here: https://github.com/n8n-io/n8n/blob/master/CONTRIBUTING.md but this is one of those nodes that may need a lot of testing if there are any chances so just having a drop-down to select the version may not work.

**Comment by idanblich** [comment]
Im using http call for now so i can use the latest endpoint

**Comment by Joffcom** [comment]
Hey @idanblich,

As nothing is really broken here for now I will mark this one as closed but when we do the update I will make sure we post an update on here so that you are aware.
