### ISSUE TITLE
# css selector not working

### ISSUE THREAD

**Issue by j2l** [n8n-io/n8n#572]
Hello,
Great project!

**Describe the bug**
Following https://community.n8n.io/t/feature-html-extraction-node-got-created/568/3 then https://n8n.io/workflows/225 I tried to extract the comic img URL from https://xkcd.com/ and it fails.

**To Reproduce**
```
{
  "name": "test",
  "nodes": [
    {
      "parameters": {},
      "name": "Start",
      "type": "n8n-nodes-base.start",
      "typeVersion": 1,
      "position": [
        650,
        210
      ]
    },
    {
      "parameters": {
        "url": "https://xkcd.com/",
        "responseFormat": "string",
        "options": {
          "followRedirect": false
        }
      },
      "name": "HTTP Request",
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 1,
      "position": [
        860,
        210
      ]
    },
    {
      "parameters": {
        "extractionValues": {
          "values": [
            {
              "key": "img",
              "cssSelector": "#comic > img"
            }
          ]
        },
        "options": {}
      },
      "name": "HTML Extract",
      "type": "n8n-nodes-base.htmlExtract",
      "typeVersion": 1,
      "position": [
        1010,
        210
      ]
    }
  ],
  "connections": {
    "Start": {
      "main": [
        [
          {
            "node": "HTTP Request",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "HTTP Request": {
      "main": [
        [
          {
            "node": "HTML Extract",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  },
  "active": false,
  "settings": {},
  "id": "1"
}
```
CSS Selector used is from "copy CSS selector" of Chrome Dev Console.
BTW even #comic throws nothing.

**Expected behavior**
get an image url

**Environment (please complete the following information):**
 - OS: Ubuntu 19.10 host, n8n:latest container
 - n8n Version 0.67.3
 - Node.js Version from container

**Additional context**
Again, great project :)

**Comment by janober** [comment]
Thanks a lot @j2l really great to hear that you enjoy n8n!

I had a look at your problem. It turns out that it is not a bug the node has simply not the correct values set. Here is the working version:

```json
{
  "nodes": [
    {
      "parameters": {
        "url": "https://xkcd.com/",
        "responseFormat": "string",
        "options": {
          "followRedirect": false
        }
      },
      "name": "HTTP Request",
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 1,
      "position": [
        520,
        340
      ]
    },
    {
      "parameters": {
        "extractionValues": {
          "values": [
            {
              "key": "img",
              "cssSelector": "#comic > img",
              "returnValue": "attribute",
              "attribute": "src"
            }
          ]
        },
        "options": {}
      },
      "name": "HTML Extract",
      "type": "n8n-nodes-base.htmlExtract",
      "typeVersion": 1,
      "position": [
        670,
        340
      ]
    }
  ],
  "connections": {
    "HTTP Request": {
      "main": [
        [
          {
            "node": "HTML Extract",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  }
}
```

So to describe the problem. You had selected for "Return Value" -> "Text" but an image does not have a Text. Only something like a div, span or similar contains any text so the output (nothing) was 100% correct. What you are apparently interested in, is the value of an attribute. So as "Return Value" -> "Attribute" has to be selected instead. And then as "Attribute" -> "src" has to be set as you want to get the image URL which is set there.

In the future please post first in the forum under https://community.n8n.io/ unless you are 100% sure that it is really a bug. Like that, we have all the questions in a single location and if another person has the same problem again in the future they can find it easily. Thanks!

**Comment by j2l** [comment]
Alrighty, thanks!

**Comment by janober** [comment]
No problem. Have fun!
