### ISSUE TITLE
HTTP Request with "Never error" fails on "ECONNREFUSED"

### ISSUE THREAD

**Issue by nesretep-anp1** [n8n-io/n8n#5758]
**Describe the bug**
For connecting to a special API - where we EXPECT having it fail sometimes - we want to react on the response status INCLUDING if it failed. We use HTTP Request node with "Never error" switched on. We expected to return with a special error JSON or something like that (due to "Never error" is active), but it fails (calling the error workflow).

**To Reproduce**

1. Use a HTTP Request node to an endpoint/port where nothing listens.
2. Switch on "Never error".
3. The execution will fail with "ERROR: UNKNOWN ERROR - check the detailed error for more information
connect ECONNREFUSED"

**Expected behavior**
The HTTP Request node should - with "Never error" activated - return something like the following:
```
[
{
"statusCode":0,
"statusMessage":"ERROR: UNKNOWN ERROR - check the detailed error for more information
connect ECONNREFUSED"
}
]
```

**Environment (please complete the following information):**

- Ubuntu Linux 22.04
- n8n Version 0.218.0
- Node.js Version 16.19.1
- Database system Postgres
- Operation mode main

**Additional context**
We already have an open issue (proven bug) in "Never error" context: #5623 -- However, this is only a hint, because this is probably not in relation.

**Comment by Joffcom** [comment]
Hey @nesretep-anp1,

I am not sure I understand this one, The Never Fail option is based on the Response from the HTTP Request if the response is not being completed because of a DNS or timeout issue I would expect it to fail. If you wanted it to actually continue you would need to use the "Continue On Fail" option under the Nodes settings which will give you an output you can use in an If node or similar to work out if there was an error.

![image](https://user-images.githubusercontent.com/4688521/227508685-b651f286-d146-4d96-b9ac-80561a560b28.png)

**Comment by Joffcom** [comment]
Hey @nesretep-anp1,

For now I am going to mark this as closed, If you have any further details to reproduce let me know and we can open it again.
