### ISSUE TITLE
Microsoft To Do get many returns all tasks

### ISSUE THREAD

**Issue by JaCoB1123** [n8n-io/n8n#5912]
Hi,

I just noticed that "Task: get many" for Microsoft To Do returns all items. I would have expected it not to return completed items (by default at least), as it is the case for e.g. ClickUp.

Is there a way to get that behavior right now other than filtering afterwards?

# Steps to reproduce the behavior:

- Create a new MS To Do node
- Select Task, Get Many and activate Return All

**Comment by Joffcom** [comment]
Hey @JaCoB1123,

Currently this node is working how I would expect it to as it is being told to return all items and it is doing exactly that, I can see why having a filter in the node to only get active would be very useful.

As we use GitHub to track issues rather than feature requests would you be able to pop open a feature request on our [Community Support Forum](https://community.n8n.io) and we can look at adding it in.
