### ISSUE TITLE
When clicking "Execute Workflow node" nothing happens

### ISSUE THREAD

**Issue by onlineapps-cloud** [n8n-io/n8n#5986]
hi, when i click  "Execute Workflow node", my workflow not executed, what i doing wrong?
n8n Version: 0.222.2
video demonstration:

https://user-images.githubusercontent.com/69077240/232249553-29e8b6c1-4a57-4269-a5df-ffd2ff6480e2.mp4

**Comment by Joffcom** [comment]
Hey @onlineapps-cloud,

I have watched the video twice now and I am not sure what the issue is that you are reporting.

I can see you running each node individually but not with the execute workflow button at the bottom of the page.

At the moment this doesn't look to be a bug, can you clarify what the issue is and maybe complete the template we provide which will help.

**Comment by onlineapps-cloud** [comment]
hi, in my mean, when i click, on execute workflow, need to execute gotify, like in node red, but gotify not executed, if gotify not executed when i execute first node, then what do this node? in gotify say, that it will execudet when i will click execute workflow, bu this not happens
![image](https://user-images.githubusercontent.com/69077240/232279929-0e42e0fa-a6f0-401a-8c03-b834b4c14a05.png)

**Comment by onlineapps-cloud** [comment]
i created a workflown an cliecked execute node
![image](https://user-images.githubusercontent.com/69077240/232280102-d78f16f0-b3e3-4fbc-9172-70a4745a3a67.png)
node executed but not happens, this node is connected to gotify, that need to be triggered when i execute first node, or in your software is not like in node-red ?

**Comment by onlineapps-cloud** [comment]
![image](https://user-images.githubusercontent.com/69077240/232280370-b07748ea-1692-449b-bfd9-f6b7c3e5bf4a.png)
here say :This node is where a manual workflow execution starts. but in fakt nothig happens. what do this node if it's not start second node?

**Comment by onlineapps-cloud** [comment]
https://user-images.githubusercontent.com/69077240/232286395-88c6d003-b3ae-48bd-8dcf-30f63d62b9b0.mp4

at the end we have in n8n 2 nodes that can trigger workflow.
1.  When clicking "Execute Workflow"  Red button on bottom page
2.  Webhook that can be triggered remotely, also as you can say in video, i don't run this node in listening mode, but it's working anywai, this is bug?
with second node all clear, question is, what happens when i execute first node? when i click on execute node button.

**Comment by onlineapps-cloud** [comment]
https://user-images.githubusercontent.com/69077240/232286798-e39c8d30-368d-4ecc-8eac-c49e9b102b7e.mp4


when i click execute node, gray line is transformed in green line, what this mean? that signal from manual execution workflow going to gotify node and gotify node will be trigeered, yes? in fact this not happens, so, i suppose that you have logical bug in execution of workflow.
![image](https://user-images.githubusercontent.com/69077240/232286784-ba985732-ebb4-483e-9a14-8eaa9fcc4d9a.png)

**Comment by onlineapps-cloud** [comment]
how to manually execute workflow now?

https://user-images.githubusercontent.com/69077240/232288073-6a637c4b-6621-44e4-8157-31ec955570d3.mp4

exactly, you cannot execute workflow manually,  when you have web hook node, you cannot execute workflow from execute node, because play button is fake!, great, i need to disconnect web hook, and click execute workflow button, it's not cool guys, please make execute node button to work and all will work fine.

**Comment by onlineapps-cloud** [comment]
https://user-images.githubusercontent.com/69077240/232289086-d539c3bd-2590-4588-8481-695ed34151cd.mp4

something is broken.

**Comment by Joffcom** [comment]
Hey @onlineapps-cloud 

Nothing is broken that I can see, when you click that play button it starts one node, if you want to run the entire workflow you would use the execute workflow button at the bottom of the screen.

When you add another trigger node like a webhook it becomes the node that will run for the test, what we don't do and what we should have in the future is an option to select which node is starting the workflow when the execute button is pressed.

As this is not a bug and intentional I am going to mark this as closed, it may be worth opening a post on the support forum if you have more questions on how to run workflows.
