### ISSUE TITLE
Telegram Trigger (probably any webhook) doesn't work with BasicAuth

### ISSUE THREAD

**Issue by rebelcode-xr** [n8n-io/n8n#604]
The "Telegram Trigger" doesn't work with BasicAuth active: the webhook is not accessible since it requires the authentication.

**To Reproduce**
1. Install n8n with docker
2. Activate the Basic Auth
3. Create a Telegram Trigger
4. Test the trigger
5. Telegram API  response:
`{"ok":true,"result":{"url":"https://n8n.website.com/webhook-test/1/telegram%20trigger/webhook","has_custom_certificate":false,"pending_update_count":11,"last_error_date":1590853845,"last_error_message":"Wrong response from the webhook: 401 Unauthorized","max_connections":40,"allowed_updates":["message"]}}`

**Expected behavior**
I expected that the webhook was accessible, even if the N8N interface is not...

**Comment by janober** [comment]
Did you try without basic-auth activated? Because I expect that it does also not work then.

Because if you activated basic-auth as described here:
https://docs.n8n.io/#/security
It does not check it for webhook URLs. So the problem you are having must be something else. How do you have n8n set up? Do you have anything else in front of it which could block access to those URLs?

In the future please always post in the community-forum (https://community.n8n.io/) first and only post here if you are 100% sure that it is a bug. Only like that can we make sure that if people have the same problem as you face right now in the future, they find the answer easily. Thanks a lot!

**Comment by rebelcode-xr** [comment]
I found out the real problem: it was a "human communication bug" :P I'm not the one who had access to the server so the "Basic Auth" was not made with N8N commands: I assumed it was...our mistake! ;)
I'm really sorry to make you lose time, but we've been trying to make it work for days (reading the guide and the forum), so when it finally worked I assumed we did everything "by manual". 🙏

**Comment by janober** [comment]
No problem. Great to hear that you got it finally working.

Have fun!
