### ISSUE TITLE
N8N_PORT configures local server port and public url port

### ISSUE THREAD

**Issue by michaeljguarino** [n8n-io/n8n#6146]
**Describe the bug**
When deploying n8n behind a load balancer, you want to configure N8N_PORT, N8N_HOST, and N8N_PROTOCOL to something like ``443, `your.loadbalancer.host` and `https` to properly format urls in the n8n ui (or at least this is the only way I can figure out based on the config schema how to do this.  Unfortunately this also forces your local server to serve off 443 which restricts the ability to containerize the server w/o running as root or can hit cloud-specific limitations.  Ideally those two concerns are separate, and the public url can be specified independently of the server port.

**To Reproduce**
(not sure how to specify repro steps since it's a configuration bug)

**Expected behavior**
independent configuration of server port and url port

**Environment (please complete the following information):**

- OS: [e.g. Ubuntu Linux 22.04]
- n8n Version [e.g. 0.200.1]
- Node.js Version [e.g. 16.17.0]
- Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed]
- Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `own`]

**Additional context**

**Comment by Joffcom** [comment]
Hey @michaeljguarino 

I am not sure I understand the issue here? You can use port 443 if you wanted to but the most common approach is to use 5678 with a reverse proxy listening on 443 to redirect the traffic.

In this configuration you only need to set the webhook_url to the domain used for the reverse proxy and all should be good.

Docs: https://docs.n8n.io/hosting/environment-variables/configuration-methods/#webhook-url

Does this maybe solve the issue you are seeing?

**Comment by michaeljguarino** [comment]
Oh I think this would work, I was looking just at https://github.com/n8n-io/n8n/blob/master/packages/cli/src/config/schema.ts and could not find that override

**Comment by Joffcom** [comment]
@michaeljguarino that is interesting, what made you take the source route over the docs?

**Comment by Joffcom** [comment]
Hey @michaeljguarino,

I am going to mark this one as closed as I suspect everything is all good now. If it isn't let me know and we can open it again.
