### ISSUE TITLE
n8n hangs when custom port and protocol are used

### ISSUE THREAD

**Issue by maurimuchico-work** [n8n-io/n8n#6286]
**Describe the bug**
If you set N8N_PORT=443 and N8N_PROTOCOL=https, n8n hangs indefinitely

**To Reproduce**
1. Register n8n custom port 443 using the environment variable N8N_PORT
2. Register n8n custom protocol https using the environment variable N8N_PROTOCOL
3. Start n8n
![n8n error](https://github.com/n8n-io/n8n/assets/123373946/f737376c-97a2-4cae-aa39-7d5d0a5478ae)

**Expected behavior**
n8n should run with TLS service enabled on port 443

**Environment (please complete the following information):**
OS: Ubuntu 22.04.2 LTS
n8n: 0.227.1
Node: v18.16.0
Database: sqlite
Operation mode: main

**Additional context**
- The database used was a new one.
- If you use the default values for N8N_PORT AND N8N_PROTOCOL, n8n runs ok:
![n8n ok](https://github.com/n8n-io/n8n/assets/123373946/291c9d94-62f9-4f1f-809b-b0d4c52d1d13)
- It also happens on version 0.225.2.

**Comment by Joffcom** [comment]
Hey @maurimuchico-work,

Rather than 443 does it work if you use 4443? I am not sure what user you are running as but ports under 1024 tend to require root / sudo access on Linux.

You have also not set any certificates so I would expect it to fail because of that as well.

**Comment by Joffcom** [comment]
Hey @maurimuchico-work,

I would not expect setting the certificates that n8n uses to start up an HTTPS listener to have any impact on the HTTP Request node. The error in the post is because that user is connecting to a service that is using a self signed certificate, If you were to start up n8n using a self signed certificate then tried to use the http request node to connect to n8n then you would see the same message that user has but if you connected to a site like Google or n8n.io it would connect normally.
