### ISSUE TITLE
SQLITE_ERROR: table execution_entity has no column named data

### ISSUE THREAD

**Issue by earthling-slavlius** [n8n-io/n8n#6597]
After the latest upgrade (docker container) any workflow generates the error: _SQLITE_ERROR: table execution_entity has no column named data_ 
n8n Version 0.233.1
If I'm trying to create a new workflow: _SQLITE_CONSTRAINT: NOT NULL constraint failed: workflow_entity.id_

**Comment by Joffcom** [comment]
Hey @earthling-slavlius,

Can you change the tag to `0.234.0` or `0.235.0` for your container and this will resolve the issue, We pulled the latest release yesterday and this has caused some issues.

You can find more about this here: https://community.n8n.io/t/problem-running-workflow-sqlite-error-table-execution-entity-has-no-column-named-data/27785/7?u=jon

For now I am going to mark this as closed as we are aware of the issue and have a workaround available and a fix due to be released soon.
