### ISSUE TITLE
n8n breaks with Cloudflare Polish and minify

### ISSUE THREAD

**Issue by nihaals** [n8n-io/n8n#6650]
**Describe the bug**
With Cloudflare's Polish enabled, n8n's frontend doesn't work and shows white screens.

**To Reproduce**
1. Start a n8n instance
2. Add Cloudflare's proxy in front of the instance
3. Create a [configuration rule](https://developers.cloudflare.com/rules/configuration-rules/) that sets "Polish" to `Lossless` and "Auto Minify" to `JS`
4. Go to the n8n instance and notice pages often have a blank white screen
5. Edit the configuration rule and set "Polish" to `Off` and "Auto Minify" to none
6. Do a hard refresh
7. Notice it works as expected

**Expected behavior**
n8n should work behind Cloudflare with their default settings as normal.

**Environment**
- OS: Docker `n8nio/n8n:0.236.0`
- n8n Version: 0.236.0
- Node.js Version: Docker `n8nio/n8n:0.236.0`
- Operation mode: own

**Additional context**
This has been reported before as #5543 and #6416 but the root cause or a solution wasn't found. This tracks having n8n work out of the box with common Cloudflare settings.

**Comment by Joffcom** [comment]
Hey @nihaals,

We have decided for now that as this issue is not directly with our code and it is only a problem when a third party makes changes (in this case Cloudflare) we are not going to prioritise working around this.

We may in the future revisit this but for now I am going to mark this as `closed as not planned`
