### ISSUE TITLE
External Modules Shown in Code Node 'require' keyword, but still not found

### ISSUE THREAD

**Issue by garylzimmer** [n8n-io/n8n#6881]
**Describe the bug**

![image](https://github.com/n8n-io/n8n/assets/10817594/2969d116-cfb7-4243-b52f-3a16219d8c97)
I am attempting to use puppeteer within a code node. The modules are installed to ~/.n8n/nodes/node_modules and have been explicitly allowed in the environmental vars on the left side.

**Environment (please complete the following information):**

Docker

**Comment by Joffcom** [comment]
Hey @garylzimmer 

This doesn't appear to be a bug and looks more like a general support issue which should be on our [community support forum](https://community.n8n.io).

I suspect the issue is that the package has not been correctly installed which is why it can't be found.

If you are using an external package with docker you would need to create a custom image (if using docker) and install the package globally rather than add it under the nodes directory.

If you can create a support topic on the forum and include what you have done we can take a look but when it comes to puppeteer there is more to install than just the npm package.
