### ISSUE TITLE
Bug: NocoDB node omitting filter by formula field

### ISSUE THREAD

**Issue by Rafurus** [n8n-io/n8n#7021]
n8n: 1.1.1

NocoDB node is omitting "filter by formulas" in second and onward run. 
Selected node is getting variable domain from batch node.
I checked it in postman as well and there where no errors with this. 
<img width="789" alt="image" src="https://github.com/n8n-io/n8n/assets/12428720/67db2f8d-eda4-40a7-a4c7-503e7b4073da">

First run
<img width="532" alt="image" src="https://github.com/n8n-io/n8n/assets/12428720/d403d574-977a-4a48-b388-7cffb04430dc">

Second run 
<img width="543" alt="image" src="https://github.com/n8n-io/n8n/assets/12428720/c955ce90-7b74-436f-871a-9ed381eb4115">

As you can see, second run totally omitted filters from node. Variable domain didn't changed in the loop as well.

**Comment by Joffcom** [comment]
Hey @Rafurus,

Does the Update Key Quote node output a domain in the output?

**Comment by Joffcom** [comment]
Hey @Rafurus,

That would explain it, So when you use `$json` it will use the data from the node before it. In your workflow on the first run `$json` will refer to the Split in Batches node and on the second run it will be from the Update Key Quote node but because the node only outputs a success bool it doesn't have the data you are tyring to use.

Instead you could try using `$('node name').item.json.x` and see if that helps but for now I am going to mark this as closed as it doesn't appear to be a bug and is more of a workflow issue which would be better suited to our support forum.
