### ISSUE TITLE
N8N_ENCRYPTION_KEY is not working as an env variable

### ISSUE THREAD

**Issue by wowi42** [n8n-io/n8n#713]
**Describe the bug**
in this [link](https://docs.n8n.io/reference/configuration.html#execution-data-manual-runs), the documentation explains:

> `n8n creates a random encryption key automatically on the first launch and saves it in the ~/.n8n folder. That key is used to encrypt the credentials before they get saved to the database. It is also possible to overwrite that key and set it via an environment variable.`

Unfortunately, it's not working, it keeps try to write a key in ~/.n8n/config which is different from the env

**To Reproduce**
1. setup last version of n8n (0.71.0)
2. export N8N_ENCRYPTION_KEY=xxxxxx
3. n8n start
4. cat ~/.n8n/config
5. key is different

**Expected behavior**
the stored key should be the same.

**Environment (please complete the following information):**
 - OS: Archlinux
 - n8n Version [0.71.0]
 - Node.js Version [14.4.0]

**Comment by janober** [comment]
To be honest, I do not really understand the problem. It is all working perfectly. For me, that are two different behaviors that are happening:

 1. If no config file exists it creates a random key, which it saves into the config and then gets used as an encryption key. -> Works
 2. No matter if a config file exists or not it uses the encryption key which got defined as an environment variable. -> Works

The only thing it did not do is to write the encryption key which got provided via environment variable into the config file if no such file did exist yet. I would have not expected that this is really needed. Because I thought that people either have a setup which uses the one in the config file or the one in the environment variable. This now solves the problem that people start the first time with an environment-variable but then in future runs not anymore? Or do I understand something wrong? How did this cause a problem for you?

Anyway if it seems to be a problem for you did I now "fix" it and will release with the next version.

What it will however not do, is to overwrite the data in the config if the environment variable used is different to the one in the config file.

**Comment by janober** [comment]
Got released with n8n@0.72.0
