### ISSUE TITLE
Google Sheets Column to Match On Clears when Sheets node is closed

### ISSUE THREAD

**Issue by 5and2** [n8n-io/n8n#7390]
**Describe the bug**
In the Google Sheets node when updating a row, you choose a Column to Match On. After closing the node and saving the workflow, when you open the Google Sheets node again, the Column to Match On has been cleared.

**To Reproduce**

1. Go to 'Google Sheets' node to update a row and fill all fields
2. Select a column in the Column to Match on dropdown
3. Go back to canvas and save the workflow
4. Go back into the Google Sheet node and the Column to Match on is no longer selected. No error is given.

**Expected behavior**
I expect the column chosen in the Column to Match On to stay selected after going back to the canvas. I also expect Google Sheets to update the matching row, instead of appending the row on the bottom when a match exist.

**Environment (please complete the following information):**

- OS: [e.g. Ubuntu Linux 20.04]
- n8n Version 1.9.0 (the Lang Chain Beta Version. Can confirm that Google Sheets node works as expected in Version 0.234.1
- Database system [SQLite]
- Operation mode [main]

![Screenshot 2023-10-09 152420](https://github.com/n8n-io/n8n/assets/125830296/02c8e1d7-c06c-41da-9bbd-7e8b95c69411)

**Comment by Joffcom** [comment]
Hey @5and2,

Thanks for the report, Sadly the AI beta is a couple of versions behind the main release but this issue was fixed in 1.9.1 so this won't be an issue for too much longer.

Out of interest if you repull the ai-beta image do you get the same issue? I was able to reproduce it in that version as well until I pulled the image again and now all seems good.

As this is resolved though I am going to mark this as closed and if we do an update to the ai beta image I will let you know.

**Comment by 5and2** [comment]
Hi Jon,
Thanks, and yes, repulling the image pulled Version 1.10.0 and did solve
the issue.
