### ISSUE TITLE
Node names containing unicode do not get highlighted in the inline expression editor.

### ISSUE THREAD

**Issue by sumezulike** [n8n-io/n8n#7607]
**Describe the bug**
An expression referencing a node by name with the syntax `{{ $('nodename') }}` does not get highlighted at all despite being resolved correctly if the name contains unicode characters. This seems to be a purely visual bug.

**To Reproduce**

1. Load the appended workflow.
2. Execute the workflow.
3. Open the node "Test".
4. See that the expression referencing the first Set Node is highlighted correctly and the other isn't, because the name contains a unicode dash.

**Expected behavior**
Correct highlighting for resolvables.

**Environment (please complete the following information):**

I tested this in the cloud and with the latest docker file, n8n version 1.14.2.

[Highlighting_Bug.json](https://github.com/n8n-io/n8n/files/13250752/Highlighting_Bug.json)
![image](https://github.com/n8n-io/n8n/assets/23718154/6c92d55f-1440-4cc7-8a9a-1224825bfb3b)

**Comment by Joffcom** [comment]
Hey @sumezulike,

This looks to be the same as https://github.com/n8n-io/n8n/issues/5527, I have checked the dev ticket and it is currently in backlog with a low priority as it doesn't break anything.

For now I am am going to mark this as closed so that we don't have duplicated issues, Let me know if you have any questions on this one.
