### ISSUE TITLE
Dot in node name breaks the output preview

### ISSUE THREAD

**Issue by Zetanova** [n8n-io/n8n#7612]
**Describe the bug**
If the node name contains a dot character then the output preview breaks
the item count is 1 and the preview displays "No output data returned"

**To Reproduce**
Add "monday.com" node and let the default node name and try to execute some action.

**Expected behavior**
Node output should be displayed

**Environment (please complete the following information):**

- docker image
- n8n Version [e.g. 1.14.2]

**Comment by Joffcom** [comment]
Hey @Zetanova,

Thanks for the report, this issue was originally reported here: https://community.n8n.io/t/bug-report-name-of-node-affects-output-data/31674 and has an internal dev ticket id of `node-866` / `ado-1244`.

As we are aware of this from our support forum I am going to mark this as closed so we don't have duplicate issues opened. Thanks again for taking the time to report this and let me know if you have any questions on this.
