### ISSUE TITLE
Compare Datasets Node, item appears in Different Branch if inputA and inputB has "null" value

### ISSUE THREAD

**Issue by oleksandrborniak** [n8n-io/n8n#7861]
**Describe the bug**
If inputA and inputB contain a "null" value it appears in a Different Branch.
<img width="210" alt="Screenshot 2023-11-29 at 12 07 07" src="https://github.com/n8n-io/n8n/assets/49722408/695fab48-420e-4522-929d-6f5b29e5752a">

**To Reproduce**
<img width="1479" alt="Screenshot 2023-11-29 at 13 04 06" src="https://github.com/n8n-io/n8n/assets/49722408/d9d2af23-e206-4dc2-a432-f61419e472fd">
<img width="1511" alt="Screenshot 2023-11-29 at 13 04 49" src="https://github.com/n8n-io/n8n/assets/49722408/5d9357c9-5f1a-4cf1-bc9a-cbfc882af321">

**Expected behavior**
If inputA and inputB have the same value (even if it is null) they should appear in Same Branch.

**Environment (please complete the following information):**

OS: MacOS
n8n Version: 1.17.1
Database system: SQLite

**Comment by Joffcom** [comment]
Hey @oleksandrborniak, 

Thanks for the report, this is an interesting one as looking at your example images one is `null` and the other is `undefined` which are both differnet it then looks like on the output because we are comparing it and setting the key to output it you see it as `null`.

I would say that based on the difference between null and undefined this is working as expected but if you wanted null and undefined to be treated as the same you could try enabling the `Fuzzy Compare` option to see if that works as you would expect.

**Comment by oleksandrborniak** [comment]
@Joffcom Thank you for the explanation.
You are totally right. 
I can use "Edit Fields (Set)" Node and expressions like
`{{ $json.color == undefined ? $json.color = null :  $json.color }}`
in order to lead to one type or enable Fuzzy Compare option.

Have a nice day!
