### ISSUE TITLE
Invalid Webhook URL in Manual Chat Trigger

### ISSUE THREAD

**Issue by dominikmukrecki** [n8n-io/n8n#8064]
### Bug Description

**Issue:** The n8n Chat widget's webhook URL is not functioning correctly when embedded in a website.

**Embed Methods Tried:**
- CDN Embed
- Vue Embed
- React Embed
- Other

**Embedding Code Used:**
```html
<link href="https://cdn.jsdelivr.net/npm/@n8n/chat/style.css" rel="stylesheet" />
<script type="module">
  import { createChat } from 'https://cdn.jsdelivr.net/npm/@n8n/chat/chat.bundle.es.js';

  createChat({
    webhookUrl: 'https://[redacted]/webhook'
  });
</script>
```

### Steps to Reproduce

1. Create a workflow with a manual chat trigger.
2. Embed the provided code on a website.

### Expected Behavior

The expected behavior is a correctly functioning chat widget with a valid webhook URL.

### Environment Details

- Deployment: Docker, Swarm, Queue Mode
- License: Enterprise License
- Version: 1.21.1

**Comment by janober** [comment]
This is not a bug. It is rather expected behavior right now as the Manual Chat Trigger node is only there to manually trigger a workflow to test it (so via the internal built-in chat). If you want to use the chat widget, you have to create a Webhook-Node yourself and use the appropriate Webhook-URL. 
That will be different once the upcoming "Chat Trigger" node got released. That one has the Webhook functionality built-in.
You can find the PR here:
https://github.com/n8n-io/n8n/pull/7409/
