### ISSUE TITLE
Microsoft SQL - Maximum call stack size exceeded

### ISSUE THREAD

**Issue by gehal4** [n8n-io/n8n#8333]
**Describe the bug**
There is an exception when using Microsoft SQL node and executing the query (Execute query - operation), when extracting the table with more then 120000 records.
The error message is :  `Maximum call stack size exceeded`

**To Reproduce**

1. Create a workflow
2. Create a node with execute query and extract a table with more then 120000 records ie. 150000

**Expected behavior**

**Environment (please complete the following information):**

- OS: Windows
- n8n Version: 1.22.6
- Node.js Version: 18.16.0
- Database system 
- Operation mode: main

**Additional context**

**Comment by Joffcom** [comment]
Hey @gehal4,

Thanks for raising this, I have created `NODE-1052` as the internal ticket to get this resolved. For now as a workaround it would be worth seeing if you can load in smaller sets of data.

**Comment by netroy** [comment]
@gehal4 
We just built a docker image `n8nio/n8n:fix-microsoft-SQL-max-call-stack-issue` with a potential fix.
Unfortunately we can't release custom builds to NPM. Would it be possible for you to test a fix for this on docker?

**Comment by netroy** [comment]
> it **works** but it gets slow

We are aware of this issue, and slowly working towards reducing the resource usage of n8n on large amount of data. Unfortunately that won't be fixed by a quick PR. But, hopefully we'll have some improvements around that in this quarter. Until then I'd recommend trying different techniques to split the data up.
PS: This operation is likely a lot slower in a manual execution, and it's possible that production executions are already performing a lot better.
