### ISSUE TITLE
Chat Node giving “empty response”

### ISSUE THREAD

**Issue by eliasmainetti** [n8n-io/n8n#8393]
Hi

I'm doing a test with Code Chat Node but the response I'm getting from it when I run it in Hosted Chat mode in webpage is 
<Empty Response>

<img width="641" alt="image" src="https://github.com/n8n-io/n8n/assets/34216013/39acca9b-5bba-4186-9ff1-04fea0ebd298">

When I execute from the chat window test in N8N, there is no problem and the answer is sent. 

<img width="568" alt="image" src="https://github.com/n8n-io/n8n/assets/34216013/1dd7f1a3-9d93-4ba8-ab52-9b0242084986">

**Expected behavior**
I expect to receive the answer from my bot. 

**Environment (please complete the following information):**

- OS: docker
- n8n Version 1.24.1
- Database system: postgres
- EXECUTIONS_MODE=regular

**Comment by Joffcom** [comment]
Hey @eliasmainetti 

Can you share the workflow and how you have the chat widget configured so we can see if this a bug or a configuration issue?

**Comment by eliasmainetti** [comment]
Hi @Joffcom 

Follow the workflow: 
[ChatBot_UpBot.json](https://github.com/n8n-io/n8n/files/13983261/ChatBot_UpBot.json)

I make my chat public available and I`ve access it through the public url available in ChatTriger Node.
<img width="351" alt="image" src="https://github.com/n8n-io/n8n/assets/34216013/8ac56355-a642-42b3-985d-138cf257112e">

As I Said, from Test Chat Window my worflow is working fine

**Comment by Joffcom** [comment]
Hey @eliasmainetti,

In the workflow execution log does it show an error?

**Comment by eliasmainetti** [comment]
Hi @Joffcom , 

The workflow runs successfully. There is no error message. 
<img width="1038" alt="Captura de Tela 2024-01-19 às 08 36 58" src="https://github.com/n8n-io/n8n/assets/34216013/8f15beb8-ce24-4413-9ee9-162f38ec3453">

In logs is also possible to check that the Retrieval Q&A node sends the the response

<img width="1362" alt="image" src="https://github.com/n8n-io/n8n/assets/34216013/96fd86a9-0c85-4b04-88f0-3f8dbd31cdbb">

Thanks. 
Elias Mainetti

**Comment by Joffcom** [comment]
Hey @eliasmainetti,

That is interesting, I had a quick play when I noticed a similar issue on the forum and it seems to work great with the AI Agent node so it could be that there is an issue with Chain nodes. I don't have Pinecone set up yet to test the workflow you have but I will work somethign out.

**Comment by the-trading-ai** [comment]
I did this test this morning and the bug is always there. Here's more details :

<img width="745" alt="image" src="https://github.com/n8n-io/n8n/assets/146002639/69099751-bd2d-47ce-91e9-6e434a0e669e">

<img width="1296" alt="image" src="https://github.com/n8n-io/n8n/assets/146002639/55ad421b-a6d6-4210-b218-17057a172c95">

<img width="536" alt="image" src="https://github.com/n8n-io/n8n/assets/146002639/1daaca29-0c69-4e5e-9b3d-45748e935c9d">

My setup 
<img width="728" alt="image" src="https://github.com/n8n-io/n8n/assets/146002639/a995b8c5-82ae-4c95-b52a-314f1e84fd9f">

The chat work in backend. here's the log backend

<img width="1266" alt="image" src="https://github.com/n8n-io/n8n/assets/146002639/c763dc23-62da-4dfb-9dba-956a3f483d10">

**Comment by the-trading-ai** [comment]
This issue still exist !

**Comment by Joffcom** [comment]
Ah I forgot to create the dev ticket for this to get it fixed, will get that done as soon as I start in the morning.

**Comment by eliasmainetti** [comment]
Thanks!! I will test

**Comment by Joffcom** [comment]
Moving this to closed as it should be resolved.
