### ISSUE TITLE
stop sending spam

### ISSUE THREAD

**Issue by DanielRuf** [n8n-io/n8n#854]
To be honest, that is a bit creepy that you contact people via email just because they unstar the project @tanay1337 

> Hi Daniel,
> 
> I just saw that you unstarred the n8n repository a while back (I have that
> "Github Star -> Slack" automation from the video running myself).
> 
> It would be great to hear what made you change your mind that we can
> improve there.
> 
> Thanks a lot and have a great day!
> 
> Best,
> Tanay

**Comment by janober** [comment]
Hello @DanielRuf!

Sorry to hear that it apparently bothered you. But you can literally ignore the email, as it is the only one we send. No follow up or whatever. So I am honestly very confused, why you create this ticket here. It sounds like we did send you a lot of unwanted emails and do not stop.
I told Tanay to write to people that did unstar us. The reason is that we want to learn and improve n8n. And who would be better to tell us what to improve, than the people that "liked" us before and apparently changed their mind? Some people help us and answer, which is great, and some other people do not answer which is also fine.

Close this ticket because as written above, would there not have been any other emails anyway so we already had "stopped".

**Comment by DanielRuf** [comment]
Sure, but not via email which is a bit surprising and direct ;-)
This never happend to me in any other big project that I starred or unstarred (it's a bit like a cold call).

**Comment by DanielRuf** [comment]
You can do it on GitHub in the open as a sort of open discussion with a short survey and link to the community.

I just wanted to make clear that the way that it was done is not the best imho. Sounded like a salesman who contacts me after I cancel a contract with a company and who contacts me because of this (even if I did not want this).

Short answer: maybe I don't use n8n and so I do not need to star the project as I have no need for it.
