### ISSUE TITLE
Node Webhook does not work in versions above 1.25.0

### ISSUE THREAD

**Issue by cmconsultor23** [n8n-io/n8n#8541]
**Describe the bug**
After 1.25.0 version the webhook node does not work correctly. When trying to run it, keeps loading indefinitely. This behavior happens in the "Production URL", in "Test URL" its ok.

**Tests i did**
I created a docker stack and updated it from version 1.20.0 to 1.27.2 one by one, when I reach version 1.25.0 this problem appears

**To Reproduce**
1. Start a new workflow with webhook node.
2. Send a request to this webhook (in production mode) with browser.
3. Check "executions" in n8n.

**Expected behavior**
Success webhook execution message

**Environment (please complete the following information):**

- OS: Ubuntu 22.04 with n8nio/n8n docker image
- n8n Version: above 1.25.0
- Database system: PostgreSQL
- Operation mode: queue

**Additional context**
n8n is running behind traefik and crowdsec

**Comment by Joffcom** [comment]
Hey @cmconsultor23,

I have checked my local install and a cloud instance and I am not able to reproduce this.

Are you using a different url for production and testing and are you using webhook workers or normal workers?

It sounds like if it is loading there is a networking issue somewhere but if downgrading gets it working again there must be something else.

Does anything appear in the logs for n8n or the reverse proxy? Have you also tried connecting to the ip directly instead of using the url as well to rule out anything odd with systems between the browser and n8n?

**Comment by cmconsultor23** [comment]
I made some changes and it solved the problem.

Apparently, my docker-compose.yml had some parameterization issue. The strange thing is that I haven't made any recent modifications except for changing the version of n8n. 
Anyway, I managed to resolve it by deleting some commented test lines and restarting the stack.

Thanks for you help @Joffcom !!

**Comment by Joffcom** [comment]
That is good to hear, thanks for the update 🙏
