### ISSUE TITLE
Cannot sign in

### ISSUE THREAD

**Issue by Hongbo-Miao** [n8n-io/n8n#86]
I registered by email, but I didn't receive any email to allow me to confirm my email.
When I tried to sign in, it lets me to confirm my email first.
So now I am totally stuck here.
Any guide will be helpful! Thanks

![image](https://user-images.githubusercontent.com/3375461/67134244-1898da80-f1c6-11e9-86b2-8f4699d705e0.png)

**Comment by janober** [comment]
I just checked. It seems there is no user registered with that email. So I guess it cleaned up the account automatically because it did not get confirmed. Currently, you have to self-host n8n. If you are interested in the hosted version you can sign up here to get informed once it is ready:
https://n8n.io/hosting

Also, one important thing to mention. The website does not give access to the hosted version of n8n. It currently only allows people to share workflows they created with others.

**Comment by Hongbo-Miao** [comment]
@janober thanks, I definitely registered. Because when I try to register again with same email, it shows

> Email is already taken

![image](https://user-images.githubusercontent.com/3375461/67163710-231eb580-f327-11e9-9a4e-644de5e4dc3f.png)

**Comment by Hongbo-Miao** [comment]
@janober oh, it might be a bug, because when I registered, it is `Hongbo.Miao@outlook.com`, note it is capital `H` and `M`. You can try to search `hongbo.miao@outlook.com` in database too.

**Comment by janober** [comment]
Uh very sorry. I wanted to answer and then got side-tracked and forgot. Yes, I could find you now and did activate it manually.
