### ISSUE TITLE
n8n produces wrong links when run behind a reverse proxy with ports other than 80 or 443

### ISSUE THREAD

**Issue by aeb-dev** [n8n-io/n8n#8638]
### Bug Description

We want to serve n8n behind a reverse proxy. While serving behind a reverse-proxy we don't want n8n to run on either 80 or 443 because they are privileged ports.

This is currently  possible but when n8n produces and external link(invite link, saml redirect etc) they include the N8N_PORT which is actually wrong.

for example let's say that we have a domain n8n.example.com that resolves to the reverse proxy. Then reverse proxy forwards calls to n8n which is running on port 5678. In this setup, if you invite a user and then copy the invite link, you would see something like `n8n.example.com:5678/...`

### To Reproduce

You can use this docker-compose https://docs.n8n.io/hosting/installation/server-setups/docker-compose/#5-create-docker-compose-file

### Expected behavior

External links should only be N8N_HOST when ran behind a reverse_proxy and when N8N_PORT is not 80 or 443

### Operating System

Alpine 3.19

### n8n Version

1.27.2

### Node.js Version

v18.19.0

### Database

PostgreSQL

### Execution mode

queue

**Comment by Joffcom** [comment]
Hey @aeb-dev,

Have you set `WEBHOOK_URL` to include the url and port you want to use?

https://docs.n8n.io/hosting/environment-variables/configuration-methods/#webhook-url

**Comment by aeb-dev** [comment]
It works like a charm, thank you!

**Comment by Joffcom** [comment]
No problem, thanks for the update.

**Comment by vinay-vissh** [comment]
On my server, `Apache` is used as a reverse proxy while `n8n` runs inside a Docker container. Initially, I could access the dashboard without any issues, but I quickly noticed that the URLs for user invitation and password reset were using `http://localhost:5678/` instead of `https://my.domain.com`.

To address this, I first started a new container with the `N8N_HOST` environment variable set to `my.domain.com`, which changed the URLs to start with `http://my.domain.com:5678/`. Then, I tried launching another container with the `N8N_PORT` variable set to `80` _(and even attempted `443`)_, but that resulted in `Apache` returning a `502 Proxy Error` along with `curl: (56) Recv failure: Connection reset by peer` in `curl`. _(Ah damn. Did this cause `n8n` to run on port `80` inside the container and I did not change the port mapping in `docker start` 😅)_

In the end, setting the `N8N_EDITOR_BASE_URL` _(as could not find `WEBHOOK_URL` in documentation)_ to `https://my.domain.com` _(and removing `N8N_HOST` and `N8N_PORT`)_ did the trick. I’m not sure why I initially chose `N8N_HOST` and `N8N_PORT` over `N8N_EDITOR_BASE_URL`.

Thanks!
