### ISSUE TITLE
Versions > 1.25.1 throw `uv_os_get_passwd returned ENOENT` with a uid that does not resolve to a username

### ISSUE THREAD

**Issue by stavros-k** [n8n-io/n8n#8664]
### Bug Description

Any version after 1.25.1 fails with this error when started with a user(id) that does not exist in the container.

```
User settings loaded from: /data/.n8n/config
    SystemError: A system error occurred: uv_os_get_passwd returned ENOENT (no
     such file or directory)
    Code: ERR_SYSTEM_ERROR
```

### To Reproduce

1. Run the official container with `user: 568:568`
2. See error

### Expected behavior

Show a clear message of the reason it fails. or a warning and continue running as before

### Operating System

Docker

### n8n Version

1.27.3

### Node.js Version

18.19.1

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @stavros-k 

Can you share your exact config? We don't officially support running as a different user so I am surprised it works at all but the error seems to be unhappy with the path which isn't one we use.

**Comment by Joffcom** [comment]
Ah maybe, the bit that caught my eye was the mention of the /data folder which isn’t one we use but I am also aware that we don’t officially support using other users so this is a bit of a grey area…

It is interesting that you get the same error outside of n8n which makes me wonder if there is anything for us to actually fix here…

I will check with the team on Monday when I get back.

**Comment by stavros-k** [comment]
Sure, no rush!

I couldn't find any direct calls to os.userInfo() in your codebase, I assume its being done from another package.
Depending on how it is structured, it might be possible to try/catch it. (Assuming that the userInfo is not really required somewhere in n8n.)

Have a good weekend

**Comment by Joffcom** [comment]
@netroy do you have any thoughts on this?

**Comment by netroy** [comment]
This is happening because we [upgraded](https://github.com/n8n-io/n8n/pull/8381) `oclif` since the version of the package we were on was long deprecated. 
In this package [there is code to determine the user's shell](https://github.com/oclif/core/blob/3.18.1/src/config/config.ts#L699), which makes calls to `require('os').userInfo().shell` if `process.env.SHELL` isn't set.

As a temporary solution, can you please add the env variable `SHELL: /bin/sh` to your container? 
For a proper fix, [We'll add this to our docker images](https://github.com/n8n-io/n8n/pull/8670).
