### ISSUE TITLE
Wrong webhook path

### ISSUE THREAD

**Issue by mecurc** [n8n-io/n8n#877]
**Describe the bug**

webhooks prefixied with `/w`, but true path with no prefixes.
For example in UI i got n8n.example.com`/w`/webhook-test/{uud4} instead of n8n.example.com/webhook-test/{uud4}

**To Reproduce**
1. Create a telegram / webhook trigger
2. Open production/test tabs
2. check url

<img width="728" alt="Screenshot 2020-08-24 at 02 00 20" src="https://user-images.githubusercontent.com/33278950/90990882-93344280-e5ad-11ea-971d-cc3076b3e011.png">

**Expected behavior**
True url without prefixes

**Environment (please complete the following information):**
 - n8n Version [e.g. 0.78.0]

**Comment by janober** [comment]
Can you please provide the full configuration (best docker-compose file to reproduce).
Esp. the environment variables your are setting. Because by default would n8n not add the path `/w/`. It will only do so if it has been configured to do that.

Most simple setup to show that it does not add the path would be:
```bash
docker run -it --rm -p 5678:5678 n8nio/n8n:0.78.0
```

**Comment by mecurc** [comment]
Sorry, I made a mistake when I set up `WEBHOOK_TUNNEL_URL`.

**Comment by janober** [comment]
Ah makes sense.

Then have fun!
