### ISSUE TITLE
setup fails with 401 via Docker instance

### ISSUE THREAD

**Issue by max19931** [n8n-io/n8n#8898]
### Bug Description

docker volume create n8n_data
docker run -it --rm --name n8n -p 5678:5678 -v n8n_data:/home/node/.n8n docker.n8n.io/n8nio/n8n

on  open and fillout a little Failure message comes up "Problem setting up owner Request failed with status code 401", email is test@localhost.local, firstname is also test, as well as the Last Name.

docker logging showed only the bootup logs from the container, with the last line been 'Press "o" to open browser', which doesn't even function as the container can not spawn a app outside of the container.

### To Reproduce

docker volume create n8n_data
docker run -it --rm --name n8n -p 5678:5678 -v n8n_data:/home/node/.n8n docker.n8n.io/n8nio/n8n

open browser to the port either localhost:5678 or IP:5678 and the navigation should redirect to /setup and fill out the form with the content of the issue text and press next.

### Expected behavior

not failing

### Operating System

Docker container

### n8n Version

latest docker container 

### Node.js Version

container version 

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by netroy** [comment]
are you using http://localhost:5678/ or some other IP/hostname ?
This likely due to the auth cookie now being allowed to use only in a secure context.
You can try disabling the `secure` flag by adding `-e N8N_SECURE_COOKIE=false` to the docker run command.

**Comment by max19931** [comment]
without docker the mess it creates is even bigger as most of the required packages are deprecated!

**Comment by netroy** [comment]
> pulled up the webpage on a different maschine

Yeah, we did not anticipate that many users who are running n8n on headless system will not have `https` configured. But since there have been a couple of complaints, I'm looking into addressing this. 
Until then, can you please add the env variable `N8N_SECURE_COOKIE=false` to the docker container or setup https 🙏🏽 ?

> the setup is failing, and no logging was produced

Sorry about this. I'm working on adding explicit error message in the frontend for scenarios like these.

> most of the required packages are deprecated

We've updated quite a lot of packages since the last stable release (2 weeks ago), so hopefully soon you should not be seeing more than a couple of deprecated packages.
We are actively working towards replacing those remaining ones as well, but those packages are often 7 level deep dependencies, and not at all easy to replace.

**Comment by Joffcom** [comment]
I am going to move this to closed as it should be resolved now.
