### ISSUE TITLE
When I post data to trello - it's ok. But when I get data from trello - it's failed

### ISSUE THREAD

**Issue by cmdntd** [n8n-io/n8n#897]
There was a problem running the workflow:
400 - {"message":"URL (https://n8n.working24.net/webhook-test/150b3bd2-5654-47fa-b61c-a55a7d6263bc/webhook) not reachable. Error: self signed certificate","error":"ERROR"}

I use n8n in docker, plesk, google cloud
![n8n-io-Workflow-Automation](https://user-images.githubusercontent.com/1112881/91431163-31642900-e88a-11ea-869c-0acfa87e25b0.png)

**Comment by janober** [comment]
The error message actually describes the issue. You do not have a valid SSL certificate. Trello does only allow callback-URLs with valid certificates. For that reason, it does not work.

If you get a valid certificate it will work fine.

**Comment by cmdntd** [comment]
I set SSL, and now I see this error when execute:

There was a problem running the workflow:
Test-Webhook can not be activated because another one with the same method "HEAD" and path "150b3bd2-5654-47fa-b61c-a55a7d6263bc/webhook" is already active!

**Comment by janober** [comment]
Are you using the latest version of n8n?

**Comment by cmdntd** [comment]
Yes, it's lastest on docker
![n8n-io-Workflow-Automation](https://user-images.githubusercontent.com/1112881/91436634-b05d5f80-e892-11ea-908c-66621054ac08.png)

**Comment by janober** [comment]
Not totally true. The latest version right now is 0.79.0 but there were no changes in it regarding that functionality so the version is new enough.

Is it possible that what it is saying is true? That you had another Test-Webhook active at the same time. 

The only problem I could find in the code which could cause that issue if the pre-registration check would have failed (for whatever reason). In this case, the webhook would not have been deleted correctly (got fixed and will be released with the next version). So maybe that was the case here. Is however an edge-case so not so sure about that.

Anyway for now I would recommend to simply restart n8n (so that the internal memory gets cleaned up) and then try again.

**Comment by cmdntd** [comment]
It seems alright when restarting. I will test more. Thank you.

**Comment by janober** [comment]
Great to hear. Have fun!
