### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by lawfulsoftware** [n8n-io/n8n#9003]
### Bug Description

There are several typos in the following where `sanbox` has been used instead of `sandbox`:

https://github.com/n8n-io/n8n/blob/2aab78b058f46c7b1692503a2b3b6bfb8939c128/packages/nodes-base/nodes/PayPal/PayPalTrigger.node.ts#L167-L168

https://github.com/n8n-io/n8n/blob/2aab78b058f46c7b1692503a2b3b6bfb8939c128/packages/nodes-base/nodes/PayPal/GenericFunctions.ts#L15

https://github.com/n8n-io/n8n/blob/2aab78b058f46c7b1692503a2b3b6bfb8939c128/packages/nodes-base/credentials/PayPalApi.credentials.ts#L32

### To Reproduce

N/A

### Expected behavior

N/A

### Operating System

N/A

### n8n Version

N/A

### Node.js Version

N/A

### Database

PostgreSQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @lawfulsoftware,

Thanks for reporting this one, We are aware of this and the reason we have not changed it is because it will be a breaking change which sounds odd but the value is kept in the database so if we were to change it anyone that was using the sandbox option would find an invalid option there instead.

As we are aware of this and it isn't really a bug (nothing is broken) I am going to close this but we will address this typo in the future and similar ones.
