### ISSUE TITLE
The node "LangChain Code" can't be connected to the node "AI Agent" because they are not compatible.

### ISSUE THREAD

**Issue by fdagostino** [n8n-io/n8n#9345]
### Bug Description

I'm trying to define and connect a Langchain Code node as a custom Language Model node and I see the legend: The node "LangChain Code" can't be connected to the node "AI Agent" because they are not compatible.

I think the issue comes from Langchain Code node supplyData function always returning a Tool class object:

https://github.com/n8n-io/n8n/blob/9003c15811fe87865b96e43c11b2dc32edb2b30f/packages/%40n8n/nodes-langchain/nodes/code/Code.node.ts#L362C3-L363C1

### To Reproduce

<img width="1120" alt="image" src="https://github.com/n8n-io/n8n/assets/17678220/5ba71555-2b71-4936-9442-75c744352ca4">

<img width="702" alt="image" src="https://github.com/n8n-io/n8n/assets/17678220/9eacf6c5-3cc5-4db3-80ba-d44b0cc89a66">

### Expected behavior

I can define and connect Langchain Code node as a custom Language Model node.

### Operating System

macOS Sonoma 14.4.1 (23E224)

### n8n Version

1.30.0

### Node.js Version

20.11.1

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @fdagostino,

At the moment the Conversational Agent only works with Chat Models, the LangChain Code node only supports output as a Language Model rather than a Chat Model.

This could be a good feature request for the forum but at the moment this is working as planned, If you wanted to use the Language model it should with one of the other agent types.

It looks like you are tyring to use Azure OpenAI as well which we already have support for which may save you some time.

![image](https://github.com/n8n-io/n8n/assets/4688521/de92a0c5-3075-43af-a16e-547b55c8453d)

For now I am going to mark this as closed but let me know if you have any questions on this.

**Comment by Joffcom** [comment]
Hey @fdagostino,

That is not something I have tried myself, If the Azure nodes themselves don't support it I would raise a feature request on the support forum (https://community.n8n.io) and we can look at adding it in the future... unless you wanted to modify the node we have and pop in a PR to add support for it.
