### ISSUE TITLE
Postgres integration not outputting quoted fields

### ISSUE THREAD

**Issue by unleashit** [n8n-io/n8n#941]
**Describe the bug**
Postgres integration seems to have issues outputting quoted fields. 

**To Reproduce**
Make a query in the Postgres integration like:

`SELECT name, email, phone, message, "createdAt" FROM "Contacts"`

Output to the spreadsheet integration (haven't tried outputting to other integrations), then in my case to Nextcloud as a binary file upload. The spreadsheet is created with all fields except the quoted (createdAt). 

When you execute the postrgres node itself everything is fine and createdAt displays. 

**Expected behavior**
All queried fields should be output

**Environment (please complete the following information):**
 - OS: Ubuntu18.04
 - n8n Version: 0.81.0
 - Node.js Version: it's the docker image so whatever you use

**Additional context**
I tried using an alias like `"createdAt" as created` and that didn't help. Nor did changing the order of the fields. I didn't try massaging it out in a middle integration like the function or set.

**Comment by krynble** [comment]
Hey @unleashit sorry about the delay on this one.

Coming up with a test scenario was a bit hard so it ended up being pushed to the end of the queue.

It turns out the problem was with the data type - in this case, a Date.

I created a PR that fixes this. Should be released soon. This issue will be closed as a fix is placed but feel free to reopen if needed.
