### ISSUE TITLE
I want to add custom nodes through OpenAPI schema

### ISSUE THREAD

**Issue by try2020-code** [n8n-io/n8n#9838]
### Bug Description

I want to dify something. Adding custom nodes via OpenAPI schema makes it easy for me to load the panel design workflow, instead of having to drag in httpRequest nodes every time

like this:https://docs.dify.ai/guides/tools#tool-definition

I think a lot of people would like a feature like this

### To Reproduce

I  know I shouldn't put forward functional requirements here, but you need to register an account to enter your official website. That's not what I want

### Expected behavior

I  know I shouldn't put forward functional requirements here, but you need to register an account to enter your official website. That's not what I want

### Operating System

win11

### n8n Version

1.46.0

### Node.js Version

new

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @try2020-code 

We use GitHub issues to track bugs rather than feature requests as you noticed so I will need to close this.

If you want to create an account on the support forum to add a vote to the existing request you can, we try to keep the feature requests in one place as it makes it a lot easier to work out what users are looking for.
