### ISSUE TITLE
n8n infinite workflow

### ISSUE THREAD

**Issue by TGearie** [n8n-io/n8n#9854]
### Bug Description

Latest version 1.46.0 (Self hosted, installed via NPM), when running workflows, they will infinitely run until stopped even if the workflow has completed successfully. 
![Screenshot 2024-06-25 at 5 29 16 PM](https://github.com/n8n-io/n8n/assets/15973411/79589809-67d6-4c8d-8221-8d2d6d3a4574)

![Screenshot 2024-06-25 at 5 30 14 PM](https://github.com/n8n-io/n8n/assets/15973411/4d4ad8b5-65c7-4339-9a2d-4455b48e2e55)

Shows that the workflow completed successfully I'm 23 seconds however it doesn't show up on the UI until we click stop.

### To Reproduce

Create any workflow, and run the workflow.

### Expected behavior

Expected the workflow to update on the website after it had finished each instance of the workflow.

### Operating System

Ubuntu Linux 22.04 LTS

### n8n Version

1.46.0

### Node.js Version

18.16.0

### Database

MySQL

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @TGearie,

Are you using a reverse proxy with n8n as well? If you are do you see the same issue if you access the instance from the IP directly?

I would also recommend moving away from MySQL as we will be removing support for it soon and if possible rather than NPM I would use the Docker image which includes everything we need to run and Node 20 instead of 18.

**Comment by TGearie** [comment]
We have nginx in there also for a reverse proxy. I will have a look at this with a docker deployment.
