### ISSUE TITLE
Is n8n ai node supports the stop token setup ?

### ISSUE THREAD

**Issue by Chensem** [n8n-io/n8n#9961]
### Bug Description

I want to use the stop tokens to stop the generation , but i can't find the option on the OpenAI Chat Model

### To Reproduce

None

### Expected behavior

None

### Operating System

Ubuntu Linux 22.04

### n8n Version

1.47.3

### Node.js Version

18.0.0

### Database

SQLite (default)

### Execution mode

main (default)

**Comment by Joffcom** [comment]
Hey @Chensem 

Would you be able to ask your question on the support forum? We only use GitHub issues for bugs rather than for feature request or support.

As a starting point though did you check under the node options there should be a setting for Max Tokens which you can adjust to control how many tokens to use.
